import { Page, h2, h3, p, t, b, li, hr, quote } from '../biz_wiki/blocks';

export const page: Page = {
  title: '🏢 目标公司情报库',
  blocks: [
    p(t('覆盖四大、MBB、英国投行、科技大厂的校招流程、薪资、申请节奏。数据来自 Glassdoor / Reddit / 官网，定期更新。')),
    hr(),

    h2('四大会计师事务所'),
    p(t('四大（Big Four）是英国最大的应届生雇主群体，每年合计在英招聘数千人，Graduate Scheme 路线成熟，对国际学生相对友好。')),

    h3('Deloitte UK'),
    li(b('主要项目：'), t('BrightStart（高中生）/ Graduate Scheme / Industrial Placement')),
    li(b('申请开放：'), t('通常 9 月开放，12 月前强烈建议提交（滚动录取，名额有限）')),
    li(b('校招流程：'), t('在线申请 → 测评（数字推理/情景判断 SJT）→ HireVue 视频面试 → 线上/线下 Assessment Centre')),
    li(b('Assessment Centre 内容：'), t('小组讨论 + 个人 Case + Competency 面试 + Partner 面试')),
    li(b('应届薪资：'), t('伦敦 £35,000-£42,000；非伦敦 £28,000-£35,000')),
    li(b('国际学生签证：'), t('提供 Skilled Worker Visa 担保，但优先 PSW 持有者')),
    li(b('热门部门：'), t('Consulting / Audit / Tax / Technology / Financial Advisory')),
    li(b('Reddit 评价：'), t('流程长但透明，面试官整体友善；Consulting 部门竞争最激烈')),

    h3('KPMG UK'),
    li(b('主要项目：'), t('School Leaver / Graduate / Apprenticeship')),
    li(b('申请开放：'), t('通常 8-9 月，部分部门额满即止')),
    li(b('校招流程：'), t('在线申请 → 数值/逻辑测评 → 电话/视频面试 → Assessment Day')),
    li(b('Assessment Day 内容：'), t('书面分析练习 + 小组 Case + Competency 面试 + Partner 面谈')),
    li(b('应届薪资：'), t('伦敦 £34,000-£40,000')),
    li(b('特色：'), t('每年发布《KPMG CEO Outlook》，面试前值得读一篇；审计部门接受率相对高')),
    li(b('避坑：'), t('KPMG 非常看重 Commercial Awareness，要能聊近期商业新闻')),

    h3('EY (Ernst & Young) UK'),
    li(b('主要项目：'), t('Graduate / Intern / EY Foundation')),
    li(b('申请开放：'), t('9 月开放，建议 11 月前提交')),
    li(b('校招流程：'), t('在线申请 → EY 专属测评平台 → 视频面试 → Partner Interview（线上）')),
    li(b('EY 无 AC 环节：'), t('已取消 Assessment Centre，改为 Partner 单独面试，流程相对简短')),
    li(b('应届薪资：'), t('伦敦 £33,000-£39,000')),
    li(b('特色：'), t('EY-Parthenon（战略咨询）竞争极激烈，和 MBB 同一档次申请人')),
    li(b('国际学生友好度：'), t('中等，有已知的内部配额限制')),

    h3('PwC UK'),
    li(b('主要项目：'), t('Graduate / BrightStart / Flying Start / Work Placement')),
    li(b('申请开放：'), t('通常 8 月，Audit 额满较早')),
    li(b('校招流程：'), t('在线申请 → PwC 测评（数字+逻辑+情景）→ Digital Interview → Assessment Centre')),
    li(b('AC 内容：'), t('小组练习 + 书面练习 + Competency 面试 + Partner 面试')),
    li(b('应届薪资：'), t('伦敦 £33,000-£38,000（不同部门差异明显）')),
    li(b('特色：'), t('PwC Deals/Strategy& 部门薪资最高；Tax 部门接受率高；Technology 快速扩张')),
    li(b('申请提醒：'), t('PwC 明确要求 UCAS 240 分或同等学历，需注意等价换算')),
    hr(),

    h2('MBB 顶尖咨询'),
    p(t('MBB（McKinsey / BCG / Bain）是咨询界三巅，英国办公室竞争激烈，中国留学生通过率低但有成功路径。')),

    h3('McKinsey & Company（London）'),
    li(b('主要岗位：'), t('Business Analyst（BA）/ Junior Associate（MBA）')),
    li(b('申请时间：'), t('通常 9-10 月，Deadline 约 11 月（每年微调）')),
    li(b('流程：'), t('简历筛选 → Problem Solving Test（PST）/数字推理 → 1-2 轮 Case 面试 → 最终轮')),
    li(b('面试轮次：'), t('共 4-6 轮 Case，每轮 1 个 Case + Personal Experience Interview（PEI）')),
    li(b('PEI 考察：'), t('Leadership / Impact / Entrepreneurial Drive，用 STAR 结构回答')),
    li(b('应届薪资：'), t('BA 约 £55,000-£60,000 + Performance Bonus')),
    li(b('中国学生建议：'), t('Case 推荐用 McKinsey 官方 Practice Cases；PEI 故事要具体且有量化影响')),
    li(b('加分项：'), t('牛剑 / LBS / LSE 背景；有实习经历；能讲清楚 Impact')),

    h3('Boston Consulting Group（BCG London）'),
    li(b('主要岗位：'), t('Associate / Intern')),
    li(b('申请时间：'), t('10-11 月（英国略晚于麦肯锡）')),
    li(b('流程：'), t('简历/Cover Letter → 线上测评（Casey AI Chat） → 2-3 轮 Case')),
    li(b('Casey 测评：'), t('BCG 独有的 AI 对话式 Case，需要和 AI 讨论商业问题，约 25 分钟')),
    li(b('应届薪资：'), t('约 £55,000 + Signing Bonus')),
    li(b('BCG 特色：'), t('比 McKinsey 更注重创意和多样化视角；同学反映面试氛围相对轻松')),
    li(b('参考材料：'), t('BCG 每月发布《Perspectives》报告，面试前读 2-3 篇展示兴趣')),

    h3('Bain & Company（London）'),
    li(b('主要岗位：'), t('Associate Consultant（AC）/ Intern')),
    li(b('申请时间：'), t('11-12 月（英国最晚）')),
    li(b('流程：'), t('简历 → Written Case → 1-2 轮 Case 面试')),
    li(b('Written Case：'), t('Bain 独有，给一份报告材料，90 分钟内写分析建议，很考验结构化思维')),
    li(b('应届薪资：'), t('约 £52,000-£57,000')),
    li(b('Bain 文化：'), t('团队凝聚力很强，面试时会考察 Fit 和"是否想和这个人共事"')),
    li(b('录取特点：'), t('Bain 伦敦班级最小（约 20-30 人/年），竞争极激烈')),
    hr(),

    h2('英国本土与国际投行'),

    h3('Barclays（UK）'),
    li(b('主要项目：'), t('Graduate Analyst Programme / Spring Insight / Summer Internship')),
    li(b('部门：'), t('Investment Banking / Markets / Technology / Risk')),
    li(b('申请时间：'), t('IB 部门 9-10 月，Technology 全年滚动')),
    li(b('流程：'), t('在线申请 → HireVue → Superday（多轮面试）')),
    li(b('应届薪资：'), t('IB 分析师 £60,000-£70,000 + Bonus（第一年可达 £20,000-£40,000）')),
    li(b('特色：'), t('Barclays 总部在伦敦，英国本土感强；Markets 部门机会多于纯 IBD')),

    h3('HSBC Global Banking & Markets'),
    li(b('主要项目：'), t('Global Graduate Programme / International Management Programme')),
    li(b('申请时间：'), t('通常 8-9 月开放')),
    li(b('特色：'), t('HSBC 重视亚洲背景，中英双语是真实加分项；香港和伦敦之间有调动机会')),
    li(b('应届薪资：'), t('伦敦 £50,000-£60,000（随部门差异大）')),
    li(b('流程：'), t('在线测评 → Assessment Centre → Final Round')),

    h3('NatWest Group'),
    li(b('主要项目：'), t('Graduate Programme / Technology Scheme')),
    li(b('特色：'), t('英国本土银行，对签证担保更友好；Retail Banking / Risk / Technology 机会多')),
    li(b('应届薪资：'), t('£30,000-£40,000（低于投行，但工作生活平衡好很多）')),
    li(b('适合人群：'), t('不想做高强度 IB，但想在金融行业工作的同学')),
    hr(),

    h2('科技大厂（英国团队）'),

    h3('Amazon UK（London / Edinburgh）'),
    li(b('主要岗位：'), t('Business Analyst / Operations Manager / Programme Manager / SDE')),
    li(b('校招项目：'), t('Graduate Scheme / MBA Internship')),
    li(b('面试特色：'), t('亚马逊 Leadership Principles（LP）面试，16 条 LP 必须准备至少 2 个故事/条')),
    li(b('常被问 LP：'), t('Customer Obsession / Ownership / Dive Deep / Deliver Results / Are Right A Lot')),
    li(b('应届薪资：'), t('Business 类 £45,000-£55,000；SDE £60,000-£80,000 + RSU')),
    li(b('避坑：'), t('亚马逊面试 STAR 格式必须完整，尤其是 Result 要量化；别说"我们团队"，要说"我做了什么"')),

    h3('Google UK（London）'),
    li(b('主要岗位：'), t('Business / Account Manager / Operations / Engineering')),
    li(b('校招项目：'), t('BOLD Internship / Business Associate Program')),
    li(b('面试特色：'), t('结构化面试（Structured Interview），行为题 + General Cognitive Ability（GCA）')),
    li(b('应届薪资：'), t('Business 类 £55,000-£70,000 + Bonus + RSU')),
    li(b('特色：'), t('Google 伦敦是欧洲最大科技办公室之一，招聘量大')),

    h3('Meta UK（London）'),
    li(b('主要岗位：'), t('Business / Operations / Marketing / Data Analyst')),
    li(b('应届薪资：'), t('£60,000-£80,000 + RSU（科技大厂里最高之一）')),
    li(b('面试：'), t('行为题侧重 Analytical Thinking 和 Initiative；数据分析岗需 SQL')),
    hr(),

    h2('英国快消/零售/管理培训生'),

    h3('Unilever Future Leaders Programme'),
    li(b('项目长度：'), t('3 年轮岗，覆盖 Marketing / Supply Chain / Finance / HR')),
    li(b('应届薪资：'), t('约 £32,000-£37,000')),
    li(b('申请时间：'), t('9-10 月，AC 通常 12 月-1 月')),
    li(b('特色：'), t('全球轮岗机会；Unilever 是国际学生签证担保最友好的快消之一')),

    h3('Diageo Graduate Programme'),
    li(b('项目：'), t('Commercial / Marketing / Supply Chain')),
    li(b('应届薪资：'), t('约 £32,000-£36,000')),
    li(b('特色：'), t('Guinness / Johnnie Walker 品牌资源；商科 Case 常考酒类快消品')),

    h3('M&S / Tesco / Sainsbury\'s'),
    li(b('特色：'), t('英国本土零售，签证担保有限但机会真实；偏 Commercial / Buying / Logistics')),
    li(b('应届薪资：'), t('£28,000-£34,000')),
    li(b('适合：'), t('目标零售/快消行业，接受非伦敦工作地点的同学')),
    hr(),

    quote(b('选公司建议：'), t('四大适合"稳健型"，咨询/投行适合"高风险高回报型"，科技大厂薪资最高但竞争激烈。根据自己的 PSW 签证剩余时间和风险偏好选择申请组合。')),
  ],
};
