import { Page, h2, h3, p, t, b, li, hr, quote } from '../biz_wiki/blocks';

export const page: Page = {
  title: '🗂️ 各公司真实面试题库（按公司整理）',
  blocks: [
    p(t('来源：Glassdoor面经、Reddit r/GradJob / r/UKJobs / r/FinancialCareers、The Student Room，均为真实被问到的原题。按公司整理，方便针对性备考。')),
    hr(),

    // ══════════════════════════════════════════
    h2('一、四大会计师事务所'),
    // ══════════════════════════════════════════

    h3('Deloitte UK — Assessment Centre真实题（Consulting/Advisory）'),
    p(b('Competency面试（Partner Interview）高频原题：')),
    li(t('"Tell me about a time you had to deliver a project under significant time pressure. What was your approach?"')),
    li(t('"Describe a situation where you had to influence someone senior to change their view. How did you do it?"')),
    li(t('"Give me an example of when you had to work with someone very different from yourself. What challenges did you face?"')),
    li(t('"Tell me about the most commercially significant piece of analysis you\'ve done. What was the impact?"')),
    li(t('"Why Deloitte Consulting specifically, rather than EY-Parthenon or PwC Strategy&?"')),
    p(b('Group Exercise真实场景（2024 AC）：')),
    li(t('场景：一家中型制造公司面临数字化转型，预算有限，讨论如何在3个选项中选择优先级（ERP系统 / 客户数据平台 / 供应链自动化）')),
    li(t('时间：20分钟小组讨论 + 5分钟向评估官汇报')),
    li(b('评分重点：'), t('你有没有主动structure讨论、有没有bring in不发言的人、有没有在结尾总结出清晰建议')),
    p(b('个人Case题（Written Exercise）：')),
    li(t('给一份零售公司的财务数据和市场信息，30分钟内写一页分析建议')),
    li(t('考察：能否快速识别关键问题、是否有优先级意识、建议是否可执行')),

    h3('KPMG UK — 真实面试题'),
    p(b('HireVue视频面试高频题：')),
    li(t('"What does good client service mean to you? Give an example."')),
    li(t('"Tell me about a time you had to adapt your communication style for a different audience."')),
    li(t('"KPMG\'s values include Integrity and Excellence — give me an example of when you\'ve demonstrated one of these."')),
    li(t('"What\'s a recent business news story that interested you, and what are the implications for our clients?"')),
    p(b('Commercial Awareness真实被问到的问题：')),
    li(t('"How do rising interest rates affect the audit risk environment?"')),
    li(t('"What\'s your view on the UK housing market — what would you tell a housebuilder client right now?"')),
    li(t('"A client in the retail sector is losing market share to online competitors. Walk me through how you\'d approach diagnosing the problem."')),
    p(b('KPMG独特的书面测评（Written Exercise at Assessment Day）：')),
    li(t('收到一封来自虚拟客户的邮件，要求你在45分钟内起草一份专业回复')),
    li(t('考察：逻辑清晰、专业语气、能否识别问题背后的真实需求')),

    h3('EY UK — Partner Interview真实题（已取消AC，改为Partner 1:1）'),
    li(t('"Why EY over Deloitte or PwC — and why this specific service line?"')),
    li(t('"Tell me about a time you used data to solve a problem."')),
    li(t('"EY is going through significant transformation with AI. What do you think the role of an auditor/advisor will look like in 5 years?"')),
    li(t('"Give me an example of when you showed initiative in a team setting."')),
    li(t('"You\'re working on a client project and discover the client may have made an error in their financial statements. What do you do?"')),
    p(b('EY-Parthenon专场（战略咨询，竞争等同MBB）：')),
    li(t('"A European luxury goods company wants to enter China. Market attractiveness assessment — go."')),
    li(t('"Our client\'s revenue has declined 15% YoY. Take me through your diagnostic framework."')),

    h3('PwC UK — 真实面试题（Digital Interview + AC）'),
    p(b('Digital Interview（视频面试）题型：')),
    li(t('"Tell me about yourself and why you\'re applying to PwC." (30秒，考察结构性表达)')),
    li(t('"A client comes to you saying their costs are too high. What are the first 3 questions you ask?"')),
    li(t('"Describe a time you received feedback you disagreed with. How did you respond?"')),
    li(t('"What do you understand by \'commercial awareness\' and how have you developed yours?"')),
    p(b('AC — 小组讨论真实场景：')),
    li(t('场景：为一个慈善机构分配£500k预算，在5个提案中选2-3个，给出理由')),
    li(t('场景：一家快消公司要决定是否进入印度市场，每人有不同数据，需要整合决策')),
    li(b('避坑：'), t('PwC的评估官特别看重"能否在倾听别人后推进讨论"，不是谁说话最多谁赢')),

    hr(),

    // ══════════════════════════════════════════
    h2('二、MBB顶尖咨询'),
    // ══════════════════════════════════════════

    h3('McKinsey London — PEI + Case真实题'),
    p(b('PEI（Personal Experience Interview）高频主题和追问：')),
    li(b('Leadership:'), t('"Tell me about a time you led a group through a significant challenge." → 追问："What specifically did you do when the team disagreed?" → 追问："What would you do differently?"')),
    li(b('Impact:'), t('"Tell me about your greatest professional achievement." → 追问："How do you know it was your contribution specifically?" → 追问："What was the numerical impact?"')),
    li(b('Entrepreneurial Drive:'), t('"Tell me about a time you did something entrepreneurial." → 追问："How did you convince others to follow you?" → 追问："What did you fail at in this process?"')),
    p(b('Solve Game（McKinsey在线测评）注意事项：')),
    li(t('包含两个任务：Ecosystem Game（生态系统资源分配）+ Redrock Study（医疗数据分析）')),
    li(t('时间：约70分钟，不可暂停')),
    li(t('不是考专业知识，而是考察系统性思维和在不确定中的决策能力')),
    li(b('备考：'), t('McKinsey官网有免费的practice tasks，至少做2遍')),
    p(b('Case题型（McKinsey风格）：')),
    li(t('"A UK supermarket has seen its profit margin decline from 4% to 2% in 3 years. What are the potential causes?" — Profitability case')),
    li(t('"A private equity firm is considering acquiring a mid-size UK logistics company. What would you want to know?" — M&A due diligence')),
    li(t('"The UK government wants to reduce NHS waiting times by 30% in 5 years. How would you approach this?" — Public sector case')),

    h3('BCG London — Casey AI + Case真实题'),
    p(b('Casey AI对话式测评（BCG独有）：')),
    li(t('与AI对话，讨论一个商业问题，约25-30分钟')),
    li(t('2024年真实题目：一家欧洲食品公司的利润下降，讨论可能原因和解决方案')),
    li(t('2024年真实题目：一个英国零售商考虑推出订阅服务，评估可行性')),
    li(b('技巧：'), t('把Casey当真人面试对待，主动structure，说"Let me break this down into..."，问澄清问题')),
    p(b('Case面试真实题（2023-2024）：')),
    li(t('"A UK energy company wants to enter the EV charging market. Should they, and how?" — Market entry')),
    li(t('"An online fashion retailer\'s return rate has increased from 25% to 40% in 2 years. Diagnose and solve." — Operations')),
    li(t('"How would you size the market for robot-assisted surgery in the UK?" — Market sizing')),

    h3('Bain London — Written Case + 口头Case'),
    p(b('Written Case（Bain独有，90分钟）：')),
    li(t('2024真实题目：一份关于UK餐饮连锁公司的报告（约15页），包含财务数据、客户调研、竞争对手信息')),
    li(t('任务：用给定材料，写一份1-2页的战略建议（格式：PPT风格的bullet points）')),
    li(b('评分重点：'), t('能否快速识别关键insight、建议是否有优先级、用数据说话')),
    p(b('口头Case真实题：')),
    li(t('"A luxury hotel chain wants to open in Manchester. Size the market and recommend a location strategy."')),
    li(t('"A UK private school\'s enrollment has dropped 10% following the new VAT rules. What should they do?"')),
    p(b('Bain特别注重Fit：')),
    li(t('"Why consulting, and specifically why Bain — what do you know about our culture that makes you want to join us?"')),
    li(t('"Tell me about a time you worked in a very small, tight-knit team. What was your role?"')),

    hr(),

    // ══════════════════════════════════════════
    h2('三、投资银行'),
    // ══════════════════════════════════════════

    h3('Goldman Sachs London — Superday真实题'),
    p(b('技术类问题（IBD部门）：')),
    li(t('"Walk me through a DCF." — 必问，要能流利讲完Unlevered FCF → WACC → Terminal Value → Bridge to Equity Value')),
    li(t('"What are the three financial statements and how do they link?" — 必问')),
    li(t('"A company\'s EBITDA is £50M, it has £200M net debt, and comparable companies trade at 8x EV/EBITDA. What\'s the equity value?"')),
    li(t('"Why might an acquirer pay a premium to the target\'s current share price?"')),
    li(t('"What\'s your view on the current M&A market in [sector you mentioned in your application]?"')),
    p(b('行为类问题：')),
    li(t('"Tell me about a deal/transaction you\'ve been following. What do you think of the price paid?"')),
    li(t('"Why Goldman specifically — and why IBD rather than Markets?"')),
    li(t('"You have two competing deadlines from two MDs. How do you handle it?"')),
    li(t('"Tell me about a time you had to present complex information to a non-technical audience."')),

    h3('Barclays London — Superday真实题（IB部门）'),
    p(b('技术类：')),
    li(t('"What is the difference between Enterprise Value and Equity Value?"')),
    li(t('"If a company buys back shares, what happens to EPS, P/E, and the stock price?"')),
    li(t('"When would you use a Sum-of-the-Parts valuation vs a standard DCF?"')),
    li(t('"Talk me through the accretion/dilution analysis in an all-stock merger."')),
    p(b('Barclays特色问题：')),
    li(t('"What\'s your view on the UK banking sector\'s performance this year?"')),
    li(t('"Barclays has both a UK ring-fenced bank and a CIB. How does that structure work and what\'s the strategic rationale?"')),
    li(t('"A UK company wants to do an IPO. Walk me through the process from our perspective."')),

    h3('HSBC Global Banking — 真实面试题'),
    p(b('HSBC特色（强调亚洲视角）：')),
    li(t('"How does China\'s economic slowdown affect our corporate banking clients in Europe?"')),
    li(t('"HSBC has a unique position bridging East and West. Give me an example of a transaction where this would be a competitive advantage."')),
    li(t('"You\'re covering a Chinese company looking to list in London. What are the key challenges?"')),
    p(b('通用技术题：')),
    li(t('"What\'s the difference between a bond and a loan from a corporate\'s perspective?"')),
    li(t('"A client wants to raise £500M. Walk me through the options and when you\'d recommend each."')),

    hr(),

    // ══════════════════════════════════════════
    h2('四、科技大厂'),
    // ══════════════════════════════════════════

    h3('Amazon UK — Leadership Principles (LP) 真实题'),
    p(t('亚马逊面试100%基于16条Leadership Principles（LP），每道题必须用STAR格式，必须说"I"而非"We"。')),
    p(b('Customer Obsession（客户至上）：')),
    li(t('"Tell me about a time when you had to make a decision that was good for the customer but bad for the business in the short term."')),
    li(t('"Describe a time when you went above and beyond what was required to satisfy a customer."')),
    p(b('Ownership（主人翁精神）：')),
    li(t('"Tell me about a time you took on a project or task outside your formal role."')),
    li(t('"Describe a situation where you identified a problem and fixed it without being asked."')),
    p(b('Dive Deep（刨根问底）：')),
    li(t('"Tell me about a time you had to analyse a complex dataset to make a recommendation."')),
    li(t('"Describe a situation where your detailed investigation uncovered something others had missed."')),
    p(b('Deliver Results（交付结果）：')),
    li(t('"Tell me about a time you delivered a project under significant constraints (time, budget, resources)."')),
    li(t('"Describe a time when you had to prioritise ruthlessly to meet a deadline."')),
    p(b('Are Right A Lot（正确判断）：')),
    li(t('"Tell me about a time your judgement was questioned and you turned out to be right."')),
    li(t('"Describe a situation where you changed your position after receiving new information."')),
    p(b('Amazon Business Analyst常见技术题：')),
    li(t('"You have a 20% drop in conversion rate on Amazon.co.uk. How would you diagnose it?" — 结构化分析题')),
    li(t('"SQL：给一张orders表，写一个query找出过去30天购买超过3次的用户"')),

    h3('Google UK — 结构化面试真实题（Business岗）'),
    p(b('General Cognitive Ability（GCA）类：')),
    li(t('"How many golf balls fit in a London double-decker bus?" — 费米估算')),
    li(t('"Estimate the number of YouTube videos uploaded per day globally."')),
    li(t('"A product\'s DAU has dropped 10% in a week. How do you diagnose it?"')),
    p(b('行为类（Google用STAR+Situational）：')),
    li(t('"Tell me about a time you used data to change someone\'s mind."')),
    li(t('"Describe a project where you had to work across multiple teams with competing priorities."')),
    li(t('"Tell me about a time you had to learn something completely new to solve a problem."')),
    p(b('Google特色Business题：')),
    li(t('"How would you grow Google Maps\' revenue without changing the core product?" — 开放性产品思维')),
    li(t('"You\'re the business lead for Google Workspace in the UK. What\'s your 12-month priority?" — 商业判断')),

    h3('Meta UK — 真实面试题（Business/Operations）'),
    p(b('Analytical Thinking类：')),
    li(t('"Instagram\'s average session time has dropped 5% MoM for 3 months. What\'s happening and what do you do?"')),
    li(t('"How would you measure the success of a new Facebook feature for small businesses in the UK?"')),
    li(t('"Meta wants to expand WhatsApp Business in the UK. Size the opportunity and recommend a go-to-market."')),
    p(b('Initiative & Impact类：')),
    li(t('"Tell me about a time you spotted an opportunity and took action without being asked."')),
    li(t('"Describe a project you built from zero. What would you do differently now?"')),

    hr(),

    // ══════════════════════════════════════════
    h2('五、快消/零售管培生'),
    // ══════════════════════════════════════════

    h3('Unilever Future Leaders Programme — AC真实题'),
    p(b('Digital Interview（无面试官，AI评分）：')),
    li(t('"Tell me about a time you influenced someone without having formal authority."')),
    li(t('"Describe a situation where you had to make a decision with incomplete data."')),
    li(t('"What\'s a Unilever brand you think is underperforming? What would you do to turn it around?"')),
    p(b('Business Case（AC当天）：')),
    li(t('场景：Dove在英国市场的市占率下降2%，给出3个维度的数据（定价/消费者态度/竞争），讨论原因和解决方案')),
    p(b('Strengths面试（Unilever已转向Strengths-Based）：')),
    li(t('"When do you feel most energised at work?"')),
    li(t('"Tell me about something you\'re really proud of — could be anything, not just work."')),
    li(t('"What kind of tasks do you find easiest?"')),

    h3('Diageo Graduate Programme — 真实题'),
    p(b('Commercial Case：')),
    li(t('"Guinness 0.0（无醇版）在英国推出。估算潜在市场规模，并建议渠道策略。"')),
    li(t('"一个重要零售渠道（如Tesco）要求压价5%，否则减少货架空间。你怎么谈？"')),
    p(b('行为类：')),
    li(t('"Tell me about a time you used consumer insight to inform a decision."')),
    li(t('"Describe a time you had to adapt your approach when something wasn\'t working."')),

    h3('P&G UK — 真实题（全年Rolling，多岗位）'),
    p(b('P&G的STAR追问特别深（往往追5层）：')),
    li(t('"Tell me about a time you led a project." → 追问："Why did you choose that approach?" → 追问："What would you do differently?"')),
    li(t('"Describe a time you used data to make a recommendation." → 追问："What was the data source?" → 追问："How did you ensure the data was reliable?"')),
    p(b('P&G特色：问题非常具体，不接受泛泛而谈')),
    li(t('"你之前提到增长了20%，这20%具体是哪个业务单元，数字是怎么算的？"')),

    hr(),

    quote(b('备考建议：'), t('针对目标公司，找Glassdoor上最近2年的面经，整理出高频题目，为每道题准备一个完整的STAR故事。四大和快消主要考Competency，MBB考Case+PEI，投行考Technical+Fit，科技公司考Analytical+LP。不要用同一套故事对付所有公司。')),
  ],
};
