import { Page, h1, h2, h3, p, t, b, li, ol, hr, quote } from './blocks';

export const page: Page = {
  title: '美国商科硕士 · 逐校逐项目详解',
  blocks: [
    h1('美国商科硕士完全指南'),
    p(t('美国拥有全球最强的商学院体系。本篇聚焦硕士项目（MSF/MFin、MSBA、MiM、MS Marketing、MS Accounting 等），逐校拆解每个项目的录取要求、学费、就业数据。')),
    p(b('关键优势：'), t('STEM 认证项目可获 3 年 OPT（36 个月工作许可），选校时务必确认。')),
    hr(),

    // ─── MIT Sloan ───
    h2('MIT Sloan School of Management'),
    p(t('麻省理工学院斯隆商学院，科技+金融的完美结合。位于波士顿/剑桥，紧邻哈佛。')),

    h3('Master of Finance (MFin)'),
    li(b('学制：'), t('12 个月（可延长至 18 个月）')),
    li(b('学费：'), t('约 $85,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 120 人，国际生约 70%')),
    li(b('录取要求：'), t('GMAT 均值 730+ / GRE 325+；TOEFL 100+（建议 105+）')),
    li(b('GPA：'), t('建议 3.7+/4.0（国内 88+）')),
    li(b('工作经验：'), t('平均 2-3 年，接受应届生但不多')),
    li(b('核心课程：'), t('资产定价、公司金融、金融工程、固定收益、衍生品、量化方法')),
    li(b('项目特色：'), t('与 MIT 工学院/数学系交叉选课；Action Learning 项目；CFA 合作')),
    li(b('就业数据：'), t('平均起薪 $130,000+，90%+ 就业率')),
    li(b('主要雇主：'), t('Goldman Sachs、Morgan Stanley、Citadel、BlackRock、JP Morgan')),
    li(b('适合人群：'), t('数学/金融/工程背景，目标量化金融/投行/资管')),

    h3('Master of Business Analytics (MBAn)'),
    li(b('学制：'), t('12 个月')),
    li(b('学费：'), t('约 $82,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 75 人')),
    li(b('录取要求：'), t('GMAT 730+ / GRE Quant 167+；TOEFL 100+（建议 105+）')),
    li(b('GPA：'), t('建议 3.7+/4.0')),
    li(b('工作经验：'), t('平均 1-2 年，接受优秀应届生')),
    li(b('核心课程：'), t('机器学习、优化、数据可视化、A/B 测试、深度学习应用')),
    li(b('项目特色：'), t('Analytics Capstone 与企业合作项目（Amazon/Nike/McKinsey 等）')),
    li(b('就业数据：'), t('平均起薪 $115,000+，95%+ 就业率')),
    li(b('主要雇主：'), t('Amazon、McKinsey、BCG、Google、Meta、Microsoft')),
    li(b('适合人群：'), t('数理/CS/工程背景，目标数据科学/科技/咨询')),
    hr(),

    // ─── Columbia ───
    h2('Columbia Business School'),
    p(t('哥伦比亚大学商学院，位于纽约曼哈顿，金融就业的地理优势无与伦比。')),

    h3('MS in Financial Economics (MSFE)'),
    li(b('学制：'), t('2 年（含暑期实习）')),
    li(b('学费：'), t('约 $85,000/年（2 年总计约 $170,000）')),
    li(b('班级规模：'), t('仅约 25 人，极度精英')),
    li(b('录取要求：'), t('GRE/GMAT 极高，接近 PhD 级别（GRE Quant 170）')),
    li(b('GPA：'), t('3.8+/4.0')),
    li(b('项目特色：'), t('与经济系联合培养，偏学术/量化，适合目标 PhD 或顶尖量化岗位')),
    li(b('就业方向：'), t('对冲基金、量化交易、投行研究部、PhD 深造')),
    li(b('适合人群：'), t('数学/经济学霸，GPA/标化极高，目标顶尖量化岗位')),

    h3('MS in Business Analytics (MSBA)'),
    li(b('学制：'), t('11 个月（3 学期）')),
    li(b('学费：'), t('约 $80,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 140 人')),
    li(b('录取要求：'), t('GMAT 720+ / GRE 325+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.6+/4.0')),
    li(b('核心课程：'), t('统计建模、机器学习、数据策略、Python/R/SQL')),
    li(b('项目特色：'), t('Capstone 项目与纽约企业合作；Columbia 品牌+纽约位置')),
    li(b('就业数据：'), t('平均起薪 $110,000+，主要去向科技/咨询/金融')),
    li(b('适合人群：'), t('商科/理工背景，目标纽约科技/咨询/金融数据岗')),

    h3('MS in Accounting and Fundamental Analysis (MSAFA)'),
    li(b('学制：'), t('10 个月（2 学期）')),
    li(b('学费：'), t('约 $78,000（总计）')),
    li(b('录取要求：'), t('GMAT 700+ / GRE 320+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.5+/4.0')),
    li(b('项目特色：'), t('偏投资分析方向（非传统会计），学习用会计数据做投资决策')),
    li(b('就业方向：'), t('投资分析、买方研究、四大估值咨询')),
    li(b('适合人群：'), t('会计/金融背景，想走投资方向而非审计')),

    h3('MS in Marketing Science'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $78,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 700+ / GRE 320+；TOEFL 100+')),
    li(b('项目特色：'), t('偏量化营销，数据驱动决策，非传统品牌营销')),
    li(b('就业方向：'), t('科技公司增长/产品营销、咨询、消费品数据分析')),
    hr(),

    // ─── NYU Stern ───
    h2('NYU Stern School of Business'),
    p(t('纽约大学斯特恩商学院，位于曼哈顿格林威治村，华尔街近在咫尺。')),

    h3('MS in Quantitative Finance'),
    li(b('学制：'), t('1 年（秋季入学）')),
    li(b('学费：'), t('约 $75,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 40 人，极小班')),
    li(b('录取要求：'), t('GMAT 720+ / GRE Quant 168+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.6+/4.0')),
    li(b('核心课程：'), t('随机过程、衍生品定价、统计套利、风险管理、量化交易策略')),
    li(b('就业数据：'), t('平均起薪 $120,000+，几乎全部留在纽约金融业')),
    li(b('主要雇主：'), t('两西格玛、城堡、高盛、摩根士丹利、德银')),
    li(b('适合人群：'), t('数学/物理/金工背景，目标华尔街量化岗位')),

    h3('MS in Business Analytics'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $75,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 50-60 人')),
    li(b('录取要求：'), t('GMAT 700+ / GRE 320+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.5+/4.0')),
    li(b('核心课程：'), t('预测分析、数据基础设施、实验设计、NLP、推荐系统')),
    li(b('就业方向：'), t('科技公司数据分析、咨询数据团队、金融科技')),
    li(b('适合人群：'), t('商科/理工背景，喜欢纽约，目标科技/咨询数据岗')),

    h3('MS in Accounting'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $70,000（总计）')),
    li(b('录取要求：'), t('GMAT 680+ / GRE 315+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.4+/4.0')),
    li(b('项目特色：'), t('满足 CPA 150 学分要求，四大直通通道')),
    li(b('就业数据：'), t('95%+ 就业率，平均起薪 $80,000+')),
    li(b('主要雇主：'), t('PwC、EY、Deloitte、KPMG')),
    li(b('适合人群：'), t('目标 CPA + 四大，会计/商科背景')),
    hr(),

    // ─── Duke Fuqua ───
    h2('Duke Fuqua School of Business'),
    p(t('杜克大学福库商学院，位于北卡罗来纳州达勒姆，Team Fuqua 文化闻名。')),

    h3('Master of Quantitative Management (MQM: Business Analytics)'),
    li(b('学制：'), t('10 个月')),
    li(b('学费：'), t('约 $68,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 120 人')),
    li(b('录取要求：'), t('GMAT 700+ / GRE 320+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.5+/4.0')),
    li(b('方向选择：'), t('Finance、Marketing、Forensics (反欺诈)、Strategy')),
    li(b('核心课程：'), t('数据科学、决策分析、数据可视化、机器学习、商业应用')),
    li(b('项目特色：'), t('可选方向灵活；Team Fuqua 协作文化强；10 个月高效毕业')),
    li(b('就业数据：'), t('平均起薪 $95,000+，就业率 90%+')),
    li(b('主要雇主：'), t('Deloitte、EY、Accenture、Amazon、Bank of America')),
    li(b('适合人群：'), t('应届生或 1-2 年经验，想快速拿硕士进咨询/数据岗')),

    h3('Master of Management Studies (MMS)'),
    li(b('学制：'), t('10 个月')),
    li(b('学费：'), t('约 $65,000（总计）')),
    li(b('两个方向：'), t('Foundations of Business（商科基础）/ Duke Kunshan University（昆山杜克双学位）')),
    li(b('录取要求：'), t('GMAT 680+ / GRE 315+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.4+/4.0')),
    li(b('适合人群：'), t('非商科背景转商科，或想快速拿管理学硕士')),
    hr(),

    // ─── UCLA Anderson ───
    h2('UCLA Anderson School of Management'),
    p(t('加州大学洛杉矶分校安德森商学院，位于洛杉矶西木区，娱乐/科技/消费品行业优势。')),

    h3('Master of Science in Business Analytics (MSBA)'),
    li(b('学制：'), t('15 个月')),
    li(b('学费：'), t('约 $72,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 60 人')),
    li(b('录取要求：'), t('GMAT 710+ / GRE 322+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.6+/4.0')),
    li(b('核心课程：'), t('统计/预测模型、机器学习、因果推断、数据管理、商业应用')),
    li(b('项目特色：'), t('15 个月含暑期实习；与洛杉矶科技/娱乐公司深度合作')),
    li(b('就业数据：'), t('平均起薪 $105,000+，90%+ 就业率')),
    li(b('主要雇主：'), t('Amazon、Disney、Google、BCG、Capital One')),
    li(b('适合人群：'), t('想留南加州/科技/娱乐行业，数理背景')),

    h3('Master of Financial Engineering (MFE)'),
    li(b('学制：'), t('15 个月')),
    li(b('学费：'), t('约 $75,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 70 人')),
    li(b('录取要求：'), t('GMAT 720+ / GRE Quant 168+；TOEFL 100+')),
    li(b('核心课程：'), t('随机微积分、Monte Carlo、风险管理、固定收益、量化交易')),
    li(b('就业数据：'), t('平均起薪 $120,000+')),
    li(b('适合人群：'), t('数学/物理/工程背景，目标量化金融')),
    hr(),

    // ─── UT Austin McCombs ───
    h2('UT Austin McCombs School of Business'),
    p(t('德克萨斯大学奥斯汀分校麦库姆斯商学院，德州旗舰校，科技公司集聚地。')),

    h3('MS in Business Analytics (MSBA)'),
    li(b('学制：'), t('10 个月')),
    li(b('学费：'), t('约 $52,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 65 人')),
    li(b('录取要求：'), t('GMAT 700+ / GRE 320+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.5+/4.0')),
    li(b('核心课程：'), t('统计建模、机器学习、优化、数据可视化、行业实践')),
    li(b('项目特色：'), t('学费性价比极高（公立校）；奥斯汀科技生态（Dell/Tesla/Apple 等）')),
    li(b('就业数据：'), t('平均起薪 $95,000+，95%+ 就业率')),
    li(b('主要雇主：'), t('Deloitte、Amazon、Dell、Walmart、EY')),
    li(b('适合人群：'), t('追求性价比，愿意留德州，数据分析方向')),

    h3('MS in Finance (MSF)'),
    li(b('学制：'), t('10 个月')),
    li(b('学费：'), t('约 $50,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 690+ / GRE 320+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.5+/4.0')),
    li(b('项目特色：'), t('CFA 合作项目；公立校学费优势；与 Texas 金融行业连接紧密')),
    li(b('就业方向：'), t('投行、企业金融、投资管理、银行')),
    li(b('适合人群：'), t('金融背景，追求性价比，目标投行/企业金融')),
    hr(),

    // ─── USC Marshall ───
    h2('USC Marshall School of Business'),
    p(t('南加州大学马歇尔商学院，位于洛杉矶市中心，校友网络极其强大。')),

    h3('MS in Business Analytics'),
    li(b('学制：'), t('18 个月（含暑期）')),
    li(b('学费：'), t('约 $70,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 80 人')),
    li(b('录取要求：'), t('GMAT 700+ / GRE 320+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.5+/4.0')),
    li(b('项目特色：'), t('含暑期实习学期；与好莱坞/科技公司合作密切；USC Trojan 校友网')),
    li(b('就业方向：'), t('科技、娱乐、咨询、金融数据岗')),

    h3('MS in Finance'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $68,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 690+ / GRE 318+；TOEFL 100+')),
    li(b('项目特色：'), t('洛杉矶金融就业网络；投资分析/公司金融/房地产金融方向')),
    li(b('适合人群：'), t('目标南加州金融行业')),
    hr(),

    // ─── Michigan Ross ───
    h2('University of Michigan Ross School of Business'),
    p(t('密歇根大学罗斯商学院，Action-Based Learning 理念，位于安娜堡。')),

    h3('Master of Management (MM)'),
    li(b('学制：'), t('10 个月')),
    li(b('学费：'), t('约 $65,000（总计）')),
    li(b('录取要求：'), t('GMAT 680+ / GRE 315+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.5+/4.0')),
    li(b('工作经验：'), t('0-2 年（面向应届生）')),
    li(b('项目特色：'), t('Action-based learning；与 Ross MBA 共享资源')),
    li(b('就业方向：'), t('咨询、金融、科技管理岗')),
    li(b('适合人群：'), t('应届生，商科/非商科背景均可，目标通用管理')),

    h3('Master of Business Analytics (MBAn)'),
    li(b('学制：'), t('10 个月')),
    li(b('学费：'), t('约 $65,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 700+ / GRE 320+；TOEFL 100+')),
    li(b('项目特色：'), t('与密歇根工学院/数据科学学院交叉；底特律+芝加哥就业辐射')),
    li(b('适合人群：'), t('数理背景，目标中西部数据/科技/咨询')),
    hr(),

    // ─── Johns Hopkins Carey ───
    h2('Johns Hopkins Carey Business School'),
    p(t('约翰霍普金斯大学凯瑞商学院，医疗/生物科技+商业交叉，华盛顿特区校区。')),

    h3('MS in Finance'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $60,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 680+ / GRE 315+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.4+/4.0')),
    li(b('项目特色：'), t('CFA 合作项目；华盛顿特区+巴尔的摩双校区；医疗金融方向可选')),
    li(b('就业方向：'), t('金融服务、医疗金融、企业金融')),

    h3('MS in Business Analytics and Risk Management'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $60,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('项目特色：'), t('风险管理+数据分析交叉；JHU 品牌强')),
    li(b('适合人群：'), t('想进金融风控/数据分析，看重学校品牌')),

    h3('MS in Marketing'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $58,000（总计）')),
    li(b('项目特色：'), t('数字营销+分析导向，非传统品牌营销')),
    hr(),

    // ─── Vanderbilt Owen ───
    h2('Vanderbilt Owen Graduate School of Management'),
    p(t('范德堡大学欧文管理学院，位于纳什维尔，南方名校，小班精英教育。')),

    h3('MS in Finance (MSF)'),
    li(b('学制：'), t('10 个月')),
    li(b('学费：'), t('约 $60,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 50 人')),
    li(b('录取要求：'), t('GMAT 680+ / GRE 315+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.4+/4.0')),
    li(b('项目特色：'), t('CFA 合作项目；小班教学，教授关注度高；医疗金融方向强')),
    li(b('就业数据：'), t('平均起薪 $85,000+，就业率 90%+')),
    li(b('适合人群：'), t('金融背景，喜欢小班环境，目标 CFA + 金融行业')),

    h3('MS in Accountancy'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $55,000（总计）')),
    li(b('项目特色：'), t('CPA 直通；四大招聘活跃')),
    hr(),

    // ─── Emory Goizueta ───
    h2('Emory Goizueta Business School'),
    p(t('埃默里大学戈伊苏埃塔商学院，位于亚特兰大，可口可乐总部所在地。')),

    h3('MS in Business Analytics (MSBA)'),
    li(b('学制：'), t('10 个月')),
    li(b('学费：'), t('约 $58,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 55 人')),
    li(b('录取要求：'), t('GMAT 680+ / GRE 315+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.5+/4.0')),
    li(b('项目特色：'), t('与 Coca-Cola/Delta/UPS 等亚特兰大巨头深度合作；Practicum 项目')),
    li(b('就业数据：'), t('平均起薪 $90,000+，95%+ 就业率')),
    li(b('适合人群：'), t('目标东南部大企业/咨询，数据分析方向')),

    h3('MS in Finance'),
    li(b('学制：'), t('10 个月（1 年）')),
    li(b('学费：'), t('约 $56,000（总计）')),
    li(b('录取要求：'), t('GMAT 670+ / GRE 315+；TOEFL 100+')),
    li(b('项目特色：'), t('CFA 合作；亚特兰大 FinTech 生态')),
    hr(),

    // ─── Rochester Simon ───
    h2('University of Rochester Simon Business School'),
    p(t('罗切斯特大学西蒙商学院，金融学术传统极强（诺贝尔经济学奖背景）。')),

    h3('MS in Finance (MSF)'),
    li(b('学制：'), t('11 个月')),
    li(b('学费：'), t('约 $55,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 660+ / GRE 315+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.3+/4.0')),
    li(b('项目特色：'), t('Simon 金融学术底蕴极强；CFA 合作；奖学金慷慨')),
    li(b('就业方向：'), t('金融分析师、风险管理、企业金融、四大')),
    li(b('适合人群：'), t('金融背景，追求学术质量和性价比')),

    h3('MS in Business Analytics'),
    li(b('学制：'), t('11 个月')),
    li(b('学费：'), t('约 $52,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('项目特色：'), t('与 Eastman Kodak 等本地企业合作')),
    hr(),

    // ─── Boston College ───
    h2('Boston College Carroll School of Management'),
    p(t('波士顿学院卡罗尔管理学院，波士顿地区，校友网络强大（尤其金融业）。')),

    h3('MS in Finance (MSF)'),
    li(b('学制：'), t('1-2 年（灵活）')),
    li(b('学费：'), t('约 $55,000-$95,000（视学制）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 680+ / GRE 315+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.4+/4.0')),
    li(b('项目特色：'), t('波士顿金融就业圈；Fidelity/State Street 等资管巨头就在附近')),
    li(b('就业方向：'), t('资产管理、投行、企业金融')),

    h3('MS in Accounting'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $50,000（总计）')),
    li(b('项目特色：'), t('CPA 直通；四大雇主深度合作')),
    hr(),

    // ─── Brandeis ───
    h2('Brandeis International Business School'),
    p(t('布兰戴斯大学国际商学院，波士顿西郊，国际金融特色。')),

    h3('MS in Finance (MSF)'),
    li(b('学制：'), t('16 个月（含暑期实习）')),
    li(b('学费：'), t('约 $58,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 650+ / GRE 310+；TOEFL 95+')),
    li(b('GPA：'), t('建议 3.3+/4.0')),
    li(b('项目特色：'), t('16 个月含暑期实习；国际金融导向；CFA 合作')),
    li(b('适合人群：'), t('国际金融方向，看重实习机会和性价比')),

    h3('MA in International Economics and Finance'),
    li(b('学制：'), t('2 年')),
    li(b('学费：'), t('约 $55,000/年')),
    li(b('项目特色：'), t('经济学+金融交叉，偏宏观/政策研究方向')),
    hr(),

    // ─── Washington Olin ───
    h2('Washington University (St. Louis) Olin Business School'),
    p(t('华盛顿大学圣路易斯奥林商学院，中西部精英校，小班教学。')),

    h3('MS in Finance'),
    li(b('学制：'), t('1 年（18 个月可选）')),
    li(b('学费：'), t('约 $58,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('录取要求：'), t('GMAT 680+ / GRE 315+；TOEFL 100+')),
    li(b('项目特色：'), t('量化金融+公司金融双方向；CFA 合作；小班制')),

    h3('MS in Business Analytics'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $55,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('项目特色：'), t('与 Boeing/Centene/Bayer 等圣路易斯企业合作')),

    h3('MS in Customer Analytics'),
    li(b('学制：'), t('1 年')),
    li(b('学费：'), t('约 $55,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('项目特色：'), t('独特项目：用数据分析理解消费者行为，偏市场分析方向')),
    hr(),

    // ─── Princeton ───
    h2('Princeton Bendheim Center for Finance'),
    p(t('普林斯顿大学本德海姆金融中心，全美最学术化的金融硕士。')),

    h3('Master in Finance (MFin)'),
    li(b('学制：'), t('2 年')),
    li(b('学费：'), t('约 $57,000/年（2 年总计约 $114,000）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('仅约 25-30 人')),
    li(b('录取要求：'), t('GRE Quant 170（几乎满分）；TOEFL 100+')),
    li(b('GPA：'), t('3.8+/4.0')),
    li(b('核心课程：'), t('资产定价理论、金融计量经济学、公司金融、行为金融')),
    li(b('项目特色：'), t('极度学术化，接近 PhD 训练；2 年含暑期实习；与经济/ORFE 系共享资源')),
    li(b('就业数据：'), t('平均起薪 $135,000+')),
    li(b('主要雇主：'), t('Citadel、DE Shaw、Goldman Sachs、Bridgewater、AQR')),
    li(b('适合人群：'), t('数学/物理/工程背景，GPA/GRE 极高，目标顶尖量化/对冲基金')),
    hr(),

    // ─── CMU Tepper ───
    h2('Carnegie Mellon Tepper School of Business'),
    p(t('卡内基梅隆大学泰珀商学院，CS+商业交叉是最大特色。')),

    h3('MS in Computational Finance (MSCF)'),
    li(b('学制：'), t('16 个月（3 学期 + 暑期实习）')),
    li(b('学费：'), t('约 $93,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('班级规模：'), t('约 90 人')),
    li(b('录取要求：'), t('GMAT 720+ / GRE Quant 168+；TOEFL 100+')),
    li(b('GPA：'), t('建议 3.6+/4.0')),
    li(b('核心课程：'), t('随机微积分、金融计算、统计套利、期权理论、机器学习in Finance')),
    li(b('项目特色：'), t('CMU 的 CS/数学/统计资源；纽约/匹兹堡双校区；Bloomberg Lab')),
    li(b('就业数据：'), t('平均起薪 $125,000+，基本全员就业')),
    li(b('主要雇主：'), t('Goldman Sachs、Citadel、JPMorgan、Morgan Stanley、Bloomberg')),
    li(b('适合人群：'), t('数学/CS/工程背景，目标量化金融/金融科技')),

    h3('MS in Business Analytics (MSBA)'),
    li(b('学制：'), t('9 个月')),
    li(b('学费：'), t('约 $50,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('项目特色：'), t('CMU 技术底蕴+商业应用；速度最快的 MSBA 之一')),
    hr(),

    // ─── Cornell ───
    h2('Cornell SC Johnson College of Business'),
    p(t('康奈尔大学约翰逊商学院，常春藤名校，Ithaca + NYC 双校区。')),

    h3('Master of Science in Applied Economics and Management'),
    li(b('学制：'), t('2 年')),
    li(b('学费：'), t('约 $35,000/年（公立学费优势，限 Dyson School）')),
    li(b('录取要求：'), t('GMAT 700+ / GRE 320+；TOEFL 100+')),
    li(b('项目特色：'), t('经济学+管理交叉；学费比其他藤校便宜；Ithaca 校区')),

    h3('Cornell Tech MFE (NYC)'),
    li(b('学制：'), t('1.5 年')),
    li(b('学费：'), t('约 $75,000（总计）')),
    li(b('STEM 认证：'), t('是')),
    li(b('项目特色：'), t('在纽约 Roosevelt Island 科技校区；金融+科技交叉')),
    hr(),

    // ─── 通用信息 ───
    h2('美国商科硕士通用信息'),

    h3('STEM 认证项目清单（极重要）'),
    p(t('以下类型的项目几乎全部有 STEM 认证，可获 36 个月 OPT：')),
    li(t('Master of Finance / MS in Finance（大部分）')),
    li(t('MS in Business Analytics / MBAn（全部）')),
    li(t('MS in Financial Engineering / Computational Finance（全部）')),
    li(t('MS in Quantitative Finance（全部）')),
    li(t('MS in Marketing Science / Customer Analytics（部分）')),
    li(t('MS in Accounting（部分学校有，部分没有，务必确认）')),
    li(t('MS in Management / MiM（少部分有）')),

    h3('申请时间线'),
    li(b('Round 1'), t('：9-10 月截止')),
    li(b('Round 2'), t('：12-1 月截止')),
    li(b('Round 3'), t('：3-4 月截止（如有）')),
    p(t('国际生强烈建议 R1 申请。部分项目采用滚动录取。')),

    h3('签证与工作'),
    li(b('OPT'), t('：普通 12 个月，STEM 项目 +24 个月 = 36 个月')),
    li(b('H-1B'), t('：年度配额 85,000，中签率约 25-30%/次')),
    li(b('STEM OPT 优势'), t('：36 个月期间可参加 3 次 H1B 抽签')),
    li(b('主要 sponsor 雇主'), t('：MBB 咨询、大型科技公司、投行均 sponsor')),

    h3('费用总结'),
    li(t('顶尖项目学费：$60,000-$95,000')),
    li(t('中等项目学费：$45,000-$60,000')),
    li(t('生活费（纽约/旧金山）：$3,000-$5,000/月')),
    li(t('生活费（中小城市）：$1,500-$2,500/月')),
    li(t('1 年总费用估算：$70,000-$130,000（约 50-95 万人民币）')),
    hr(),

    quote(b('选校提醒：'), t('美国商科硕士选校三个关键因素：1) STEM 认证 2) 地理位置（就业辐射）3) 项目排名/就业数据。三者都重要，但 STEM 认证对留美工作是决定性的。')),
  ],
};
