import { Page, h1, h2, h3, p, t, b, li, ol, hr, quote } from './blocks';

export const page: Page = {
  title: '选校策略 · 六大地区横向对比',
  blocks: [
    h1('选校策略：如何确定你的目标'),
    p(t('商科留学不是"选学校"，是"选路径"。本篇帮你横向对比六大地区，找到最适合你的方向。')),
    hr(),

    h2('第一步：明确职业目标'),
    p(t('毕业后想做什么？这直接决定你应该去哪。')),
    li(b('投行/金融'), t(' → 美国（Columbia/Stern）、英国（LBS/LSE）、香港（HKU/HKUST）')),
    li(b('量化金融/金融工程'), t(' → 美国（MIT/CMU/Princeton）、英国（Imperial）')),
    li(b('咨询'), t(' → 法国（HEC/INSEAD）、美国（Duke MQM）、英国（LBS/Oxford）')),
    li(b('数据分析/科技'), t(' → 美国（MIT MBAn/UCLA MSBA）、英国（Imperial）、新加坡（NUS）')),
    li(b('回国大厂/金融'), t(' → 香港三大、新加坡 NUS/NTU、英国 G5')),
    li(b('移民/长期海外'), t(' → 澳大利亚（八大）、新加坡（PR 路径）')),
    li(b('奢侈品/时尚'), t(' → 法国（HEC/ESSEC）、意大利（Bocconi）')),
    li(b('会计/四大'), t(' → 澳大利亚（UNSW/Monash MPA）、香港（CUHK MAcc）、英国（LSE）')),
    hr(),

    h2('第二步：评估自身条件'),
    h3('背景自评清单'),
    ol(t('本科院校（985 / 211 / 双非 / 海本）')),
    ol(t('GPA（百分制 / 4.0 制）')),
    ol(t('GMAT/GRE 成绩（或预估能力）')),
    ol(t('IELTS/TOEFL 成绩')),
    ol(t('实习经验（段数、行业、公司知名度）')),
    ol(t('预算（家庭可支持的总金额）')),
    ol(t('时间（何时入学，是否接受 gap）')),
    ol(t('毕业后意向（留海外 vs 回国）')),
    hr(),

    h2('第三步：费用对比'),
    h3('1 年制 MSc Finance 总费用（含生活费）'),
    li(b('美国'), t('：$70,000-$130,000（约 50-95 万人民币）')),
    li(b('英国'), t('：£45,000-£75,000（约 40-65 万人民币）')),
    li(b('法国'), t('：€30,000-€55,000（约 23-43 万人民币）')),
    li(b('新加坡'), t('：S$55,000-$80,000（约 28-42 万人民币）')),
    li(b('香港'), t('：HK$350,000-$550,000（约 32-50 万人民币）')),
    li(b('澳大利亚（2 年）'), t('：AUD $120,000-$170,000（约 55-80 万人民币）')),
    p(b('性价比排序：'), t('法国 > 新加坡 > 香港 ≈ 英国 > 澳大利亚（2年）> 美国')),
    hr(),

    h2('第四步：毕业后工签对比'),
    li(b('美国'), t('：OPT 12 个月（STEM 项目 36 个月），需抽签 H1B')),
    li(b('英国'), t('：PSW 2 年，无条件')),
    li(b('法国'), t('：APS 1 年 + Talent Passport 4 年')),
    li(b('新加坡'), t('：LTVP 1 年 + EP 工签')),
    li(b('香港'), t('：IANG 2 年，无条件')),
    li(b('澳大利亚'), t('：PSW 2-5 年（取决于学制+地区），可走移民')),
    p(b('留海外最容易：'), t('澳大利亚 > 新加坡 > 香港 ≈ 英国 > 法国 > 美国（签证确定性）')),
    hr(),

    h2('第五步：回国认可度对比'),
    li(b('T1 最高认可'), t('：美国 M7 相关硕士、英国 G5+LBS、HEC/INSEAD')),
    li(b('T2 非常高'), t('：香港三大、新加坡 NUS/NTU、美国 T15 相关硕士')),
    li(b('T3 高'), t('：英国 Warwick/Manchester/Edinburgh、法国 ESSEC/ESCP/EDHEC')),
    li(b('T4 中等偏上'), t('：澳洲八大、香港 CityU/PolyU、法国 emlyon/SKEMA')),
    p(b('回国认可排序：'), t('美国 Top ≈ 英国 G5 > 香港三大 ≈ 新加坡 Top > 法国 Top > 澳洲八大')),
    hr(),

    h2('第六步：申请难度对比'),
    h3('985 均分 85+ / GMAT 700+ / IELTS 7.0+ 能申到什么'),
    li(b('美国'), t('：MIT MFin / Columbia MSBA / Duke MQM 有机会')),
    li(b('英国'), t('：Oxford/LSE/Imperial MSc Finance 有机会')),
    li(b('法国'), t('：HEC MiM / MSc 大概率录取')),
    li(b('新加坡'), t('：NUS MSc Finance 有机会')),
    li(b('香港'), t('：HKU/HKUST MSc Finance 有机会（要抢第一轮）')),
    li(b('澳大利亚'), t('：墨大/UNSW 稳进')),

    h3('双非均分 83+ / GMAT 650+ / IELTS 6.5+ 能申到什么'),
    li(b('美国'), t('：Rochester/Brandeis/JHU MSF 有机会')),
    li(b('英国'), t('：Warwick/Manchester/Edinburgh MSc Finance 有机会（要看名单）')),
    li(b('法国'), t('：ESSEC/ESCP/EDHEC MSc 有机会')),
    li(b('新加坡'), t('：NTU/SMU MSc 有机会')),
    li(b('香港'), t('：CUHK/CityU MSc Finance 有机会')),
    li(b('澳大利亚'), t('：八大全部有机会')),
    hr(),

    h2('选校分层策略'),
    p(t('无论申请哪个地区，都要做分层：')),
    li(b('Dream（冲刺）2-3 所'), t(' — 有距离但值得试')),
    li(b('Target（目标）3-4 所'), t(' — 条件匹配，录取概率 50%+')),
    li(b('Safety（保底）2-3 所'), t(' — 大概率录取且能接受')),
    p(t('总共申请 7-10 个项目是合理数量。跨地区混申（如香港+英国+新加坡）是常见策略。')),
    hr(),

    h2('典型组合推荐'),
    h3('组合 1：想留海外 + 预算充足'),
    li(t('Dream：美国 MIT MFin / Columbia MSBA')),
    li(t('Target：英国 LSE/Imperial MSc Finance + 新加坡 NUS MSc Finance')),
    li(t('Safety：澳大利亚 墨大/UNSW Master of Finance')),

    h3('组合 2：想回国 + 追求排名'),
    li(t('Dream：英国 Oxford/LSE MSc Finance')),
    li(t('Target：香港 HKU/HKUST MSc Finance + 新加坡 NUS')),
    li(t('Safety：英国 Warwick/Manchester + 香港 CUHK/CityU')),

    h3('组合 3：预算有限 + 看重性价比'),
    li(t('Dream：法国 HEC MiM + 香港 HKU MEcon')),
    li(t('Target：法国 ESSEC/EDHEC MSc + 新加坡 NTU/SMU')),
    li(t('Safety：香港 CityU + 澳大利亚 ANU/Adelaide')),

    h3('组合 4：双非 + 想要好排名'),
    li(t('Dream：香港 CUHK MSc Finance + 英国 Warwick MSc Finance')),
    li(t('Target：新加坡 SMU MAF + 法国 EDHEC MSc Finance')),
    li(t('Safety：澳大利亚 UNSW/Monash + 香港 CityU')),
    hr(),

    quote(b('决策公式：'), t('最终选择 = 职业目标 × 预算 × 个人偏好（地理/文化/家庭）。没有"最好"的选择，只有"最适合你"的选择。')),
  ],
};
