import { Page, h1, h2, h3, p, t, b, li, ol, hr, quote } from './blocks';

export const page: Page = {
  title: '标化考试 · GMAT / GRE / IELTS / TOEFL',
  blocks: [
    h1('标化考试完全指南'),
    p(t('标化考试是商科留学的敲门砖。考什么、考几分、什么时候考，这里全部讲清楚。')),
    hr(),

    h2('一、GMAT vs GRE：考哪个？'),
    h3('GMAT Focus Edition（2024 新版）'),
    li(t('总分 205-805，三部分：Quantitative / Verbal / Data Insights')),
    li(t('时长 2 小时 15 分钟')),
    li(t('商学院首选，尤其金融和管理硕士')),
    li(t('适合：目标明确是商科')),

    h3('GRE'),
    li(t('总分 260-340，三部分：Verbal / Quantitative / Analytical Writing')),
    li(t('几乎所有商学院都接受 GRE')),
    li(t('适合：同时申请商科+其他专业，或 verbal 不强想避免 GMAT')),

    h3('哪些项目不需要 GMAT/GRE'),
    li(b('澳洲'), t('：大部分 MSc/Master 不需要（个别推荐提交）')),
    li(b('英国'), t('：部分项目不强制（LSE/Imperial/Warwick 等推荐但非必须）')),
    li(b('香港'), t('：MSc Finance 推荐提交，其他 MSc 多数不强制')),
    li(b('新加坡'), t('：部分项目不强制')),
    li(b('美国'), t('：大部分要求（少数可 waive）')),
    li(b('法国'), t('：MiM 多数要求，MSc 部分不要求')),
    hr(),

    h2('二、GMAT 目标分数'),
    h3('按项目层级'),
    li(b('MIT MFin / Princeton MFin / CMU MSCF'), t('：GMAT 730+（GRE Quant 168+）')),
    li(b('Columbia MSBA / NYU Quant Finance / UCLA MFE'), t('：GMAT 720+')),
    li(b('LBS MiF / Oxford MSc FE'), t('：GMAT 700+')),
    li(b('HKU/HKUST MSc Finance'), t('：GMAT 680+')),
    li(b('HEC MiM / ESSEC GE'), t('：GMAT 680+')),
    li(b('NUS/NTU MSc Finance'), t('：GMAT 660+')),
    li(b('Duke MQM / Emory MSBA'), t('：GMAT 680+')),
    li(b('Warwick/Manchester/EDHEC MSc'), t('：GMAT 650+（推荐但非必须）')),
    li(b('CUHK/CityU/SMU'), t('：GMAT 620-650+')),
    li(b('Rochester/Brandeis/JHU MSF'), t('：GMAT 650+')),

    h3('中国学生 GMAT 策略'),
    li(t('Quant 部分争取满分或接近满分（中国学生优势）')),
    li(t('Verbal 和 Data Insights 是拉分关键')),
    li(t('建议考 2-3 次（每次间隔至少 16 天）')),
    li(t('有效期 5 年，不要考太早也不要太晚')),

    h3('GMAT 700+ 备考策略（来自 GMAT Club/Reddit 高分经验）'),
    p(t('GMAC 官方数据：4,200+ 考生中，700+ 的学生平均备考 121 小时。但大部分人需要 300-400 小时的有效学习。')),
    ol(b('第 1 步：诊断测试'), t(' — 做一次官方 Mock Test，了解起点（大部分中国学生首考在 600-650）')),
    ol(b('第 2 步：制定计划'), t(' — 3-6 个月备考期，每天 2-3 小时')),
    ol(b('第 3 步：打好基础'), t(' — 先把每个题型的基本概念和方法掌握（GMAT Official Guide 是核心教材）')),
    ol(b('第 4 步：刷题+错题分析'), t(' — 不是刷越多越好，每道错题都要分析原因')),
    ol(b('第 5 步：每周模考'), t(' — 在真实环境下做模考，训练体力和节奏。考后分析比做题更重要。')),
    ol(b('第 6 步：弱项突破'), t(' — 通过模考数据找到薄弱题型，集中攻克')),
    li(b('核心原则'), t('：700+ 不是靠\"学更多\"，而是靠\"学更聪明\"。理解概念 > 刷题数量。')),
    li(b('推荐资源'), t('：GMAT Official Guide / GMAT Club 题库 / Manhattan Prep / Target Test Prep')),
    hr(),

    h2('三、GRE 目标分数'),
    li(b('顶尖量化项目'), t('：Quant 168+ / Verbal 160+ / 总分 328+')),
    li(b('顶尖商科硕士'), t('：Quant 165+ / Verbal 158+ / 总分 323+')),
    li(b('一般商科硕士'), t('：Quant 163+ / Verbal 155+ / 总分 318+')),
    li(t('数学/金融/工程类项目更看重 Quant 分数')),
    hr(),

    h2('四、语言考试：IELTS vs TOEFL'),
    h3('IELTS（雅思）'),
    li(t('总分 9 分，听说读写四项')),
    li(t('英国/澳洲/香港/新加坡/欧洲更常用')),
    li(t('口语为真人对话，对部分学生更友好')),
    li(t('有效期 2 年')),

    h3('TOEFL iBT（托福）'),
    li(t('总分 120 分，听说读写四项')),
    li(t('美国院校首选')),
    li(t('机考，口语对着电脑说')),
    li(t('有效期 2 年')),

    h3('目标分数对比'),
    li(b('美国 Top'), t('：TOEFL 105+（口语 25+）/ IELTS 7.5+')),
    li(b('英国 LBS/Oxford'), t('：IELTS 7.5+（单项 7.0+）')),
    li(b('英国 LSE/Imperial'), t('：IELTS 7.0+（单项 6.5+）')),
    li(b('香港 Top'), t('：IELTS 7.0+ / TOEFL 90+')),
    li(b('香港 CityU/PolyU'), t('：IELTS 6.5+ / TOEFL 79+')),
    li(b('新加坡'), t('：IELTS 6.5-7.0 / TOEFL 85-100')),
    li(b('澳洲（大部分）'), t('：IELTS 6.5+（单项 6.0+）')),
    li(b('澳洲墨大'), t('：部分项目 IELTS 7.0+')),
    li(b('法国'), t('：IELTS 6.5-7.0 / TOEFL 90-100')),
    hr(),

    h2('五、备考时间线'),
    ol(b('申请前 12-18 个月'), t('：开始准备 GMAT/GRE，目标 3-6 个月出分')),
    ol(b('申请前 8-12 个月'), t('：GMAT/GRE 首考，不理想继续刷分')),
    ol(b('申请前 6-10 个月'), t('：准备 IELTS/TOEFL，目标 2-3 个月出分')),
    ol(b('申请前 3-6 个月'), t('：所有标化出分，开始写文书')),
    p(t('GMAT 和 TOEFL/IELTS 可以同时准备，但建议 GMAT 优先（难度更大）。')),
    hr(),

    h2('六、考试有效期'),
    li(t('GMAT：5 年')),
    li(t('GRE：5 年')),
    li(t('TOEFL：2 年')),
    li(t('IELTS：2 年')),
    p(t('语言成绩有效期短，不要考太早。建议申请前 6-12 个月考出来。')),
    hr(),

    h2('七、要不要考 GMAT？决策树'),
    li(b('只申澳洲/部分英国'), t(' → 大概率不需要，省时间')),
    li(b('申香港/新加坡/法国'), t(' → 推荐考，680+ 有明显加分')),
    li(b('申美国/LBS/Oxford'), t(' → 必须考，700+ 起步')),
    li(b('混申多地区'), t(' → 建议考，一个分数多处使用')),
    hr(),

    quote(b('考试策略：'), t('标化是门槛，不是决定因素。达到目标线后，时间投入在文书和面试上回报更大。与其从 720 刷到 740，不如把文书写好。')),
  ],
};
