/**
 * 美国商科求职知识库 - 深度内容补充（第五批）
 * Offer谈判手册 / 行为面试题库 / FAANG文化深度 / VC求职 / Cover Letter模板
 */

import * as fs from 'fs';
import * as https from 'https';
import * as path from 'path';
import * as os from 'os';

const TOKEN_FILE = path.join(os.homedir(), 'startup-7steps', '.feishu-user-token.json');
let USER_TOKEN: string;
try {
  USER_TOKEN = JSON.parse(fs.readFileSync(TOKEN_FILE, 'utf-8')).access_token;
  if (!USER_TOKEN) throw new Error('access_token 为空');
} catch (e: any) {
  console.error('❌ 无法读取用户 token:', e.message);
  process.exit(1);
}

const SPACE_ID = '7615700879567506381';
const PARENT_NODE_TOKEN = 'Adh3w4XwCiMs2zkApVhcFdT0nFf';
const DOMAIN = 'hcn2vc1r2jus.feishu.cn';

function api(method: string, urlPath: string, body?: any): Promise<any> {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const req = https.request({
      hostname: 'open.feishu.cn', path: urlPath, method,
      headers: {
        'Authorization': `Bearer ${USER_TOKEN}`,
        'Content-Type': 'application/json',
        ...(data ? { 'Content-Length': Buffer.byteLength(data) } : {}),
      },
      rejectUnauthorized: false,
    }, res => {
      let d = ''; res.on('data', c => d += c);
      res.on('end', () => { try { resolve(JSON.parse(d)); } catch (e) { reject(new Error(d.slice(0, 300))); } });
    });
    req.on('error', reject);
    if (data) req.write(data); req.end();
  });
}

const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

function t(text: string, bold = false, italic = false): any {
  return { text_run: { content: text, text_element_style: { bold, italic } } };
}
function p(...elements: any[]): any {
  return { block_type: 2, text: { elements, style: {} } };
}
function h2(text: string): any {
  return { block_type: 4, text: { elements: [t(text, true)], style: {} } };
}
function h3(text: string): any {
  return { block_type: 5, text: { elements: [t(text, true)], style: {} } };
}
function li(...elements: any[]): any {
  return { block_type: 12, text: { elements, style: {} } };
}
function ol(...elements: any[]): any {
  return { block_type: 13, text: { elements, style: {} } };
}
function hr(): any { return { block_type: 22 }; }
function quote(...elements: any[]): any {
  return { block_type: 15, text: { elements, style: {} } };
}

async function writeBlocks(objToken: string, blocks: any[]) {
  const CHUNK = 50;
  for (let i = 0; i < blocks.length; i += CHUNK) {
    const chunk = blocks.slice(i, i + CHUNK);
    const r = await api('POST', `/open-apis/docx/v1/documents/${objToken}/blocks/${objToken}/children`, {
      children: chunk, index: i,
    });
    if (r.code !== 0) console.error(`  ❌ block写入失败: ${r.code} ${r.msg}`);
    else console.log(`  ✓ 写入 blocks ${i}-${Math.min(i + CHUNK, blocks.length) - 1}`);
    await sleep(400);
  }
}

async function createPage(title: string, blocks: any[]): Promise<string | null> {
  console.log(`\n📄 创建页面：${title}`);
  const r = await api('POST', `/open-apis/wiki/v2/spaces/${SPACE_ID}/nodes`, {
    obj_type: 'docx',
    parent_node_token: PARENT_NODE_TOKEN,
    node_type: 'origin',
    title,
  });
  if (r.code !== 0) { console.error(`  ❌ 创建失败: ${r.code} ${r.msg}`); return null; }
  const nodeToken = r.data?.node?.node_token;
  const objToken = r.data?.node?.obj_token;
  console.log(`  node_token: ${nodeToken}`);
  await sleep(600);
  await writeBlocks(objToken, blocks);
  console.log(`  ✅ https://${DOMAIN}/wiki/${nodeToken}`);
  return nodeToken;
}

// ============================================================
// 页面1：💰 Offer谈判完整手册（美国职场实战）
// ============================================================
const offerNegotiationBlocks: any[] = [
  p(t('来源：Levels.fyi、LinkedIn、Reddit r/cscareerquestions、Glassdoor谈判指南、Harvard Business Review谈判研究，综合数百位求职者真实经验。', false, true)),
  hr(),
  h2('一、核心原则：为什么你必须谈判'),
  p(t('80%以上的美国雇主开出的initial offer都有谈判空间。LinkedIn调查：只有37%的求职者每次都谈判，但87%的招聘经理表示offer从未因谈判被撤回。不谈判= 直接损失$10,000-$50,000/年。')),
  li(t('应届生可谈空间：'), t('$5,000-$20,000 base + RSU池 + signing bonus', true)),
  li(t('有竞争offer者谈判空间：'), t('可再提升15-25%的total comp', true)),
  li(t('内推/referral候选人谈判空间：'), t('通常比冷申请大10-15%', true)),
  li(t('关键心理：招聘方已经花了大量时间选你，撤offer成本极高，谈判几乎零风险')),
  hr(),
  h2('二、谈判时机与流程'),
  h3('Step 1: 收到口头Offer时的标准回应'),
  quote(t('"Thank you so much for the offer — I\'m really excited about this opportunity. I\'d like to take a few days to review the details carefully. When do you need my decision by?"')),
  p(t('关键点：永远不要当场接受。要求至少3-5个工作日。标准deadline是1-2周。')),
  h3('Step 2: 研究市场行情（必做）'),
  li(t('Levels.fyi：科技公司最精准的TC数据，可按职位/城市/经验筛选')),
  li(t('Glassdoor Salary：各行业基础薪资参考')),
  li(t('LinkedIn Salary Insights：需Premium，但数据覆盖广')),
  li(t('H1B Salary Database (h1bdata.info)：实际申报工资，法律要求真实')),
  li(t('Blind App：同公司同职位匿名分享，最真实')),
  li(t('WSO Compensation Report：金融行业最权威年度调查')),
  h3('Step 3: 第一次counter offer的表达方式'),
  quote(t('"I\'m very excited about joining [Company]. Based on my research on market rates for this role in [City], and considering my background in [X], I was hoping we could get the base salary to [具体数字]. Is that something you\'d be able to work with?"')),
  p(t('注意：给出具体数字，不要给range（给range对方会取低值）。数字比目标高10-15%。')),
  hr(),
  h2('三、可谈判的所有项目（不只是base salary）'),
  h3('薪酬结构拆解'),
  li(t('Base Salary：'), t('最稳定，影响未来涨薪基础，优先级最高', true)),
  li(t('Signing Bonus：'), t('一次性，不影响base，公司最容易让步的部分', true)),
  li(t('RSU（Restricted Stock Units）：'), t('科技公司核心，4年vesting，cliff后才能卖', true)),
  li(t('Annual Bonus Target：'), t('通常按base%计算，提高base同时提高bonus基数', true)),
  li(t('Equity Refresh：'), t('每年performance review后追加RSU，可问政策', true)),
  h3('非货币福利也可谈'),
  li(t('Start Date：多要2-4周，处理个人事务')),
  li(t('Work from Home：可谈remote days或全远程')),
  li(t('Title/Level：从L4谈到L5，长期影响极大')),
  li(t('Relocation Package：$5,000-$15,000 搬家补贴')),
  li(t('PTO（带薪休假）：标准15天，可谈到20天')),
  li(t('Professional Development Budget：培训/会议经费$1,000-$5,000/年')),
  li(t('401k Match Vesting Schedule：加速vesting时间表')),
  hr(),
  h2('四、竞争Offer的使用方法（最强谈判筹码）'),
  h3('如何leverage竞争offer'),
  quote(t('"I have a competing offer from [Company] that I need to respond to by [date]. The total compensation is around [数字]. I\'d really prefer to join [Target Company], but I need to make sure the numbers are comparable. Is there anything you can do?"')),
  p(t('注意事项：')),
  li(t('不要撒谎关于竞争offer——如果被发现，offer会被撤回')),
  li(t('不需要透露所有细节，说"around $XXX total comp"即可')),
  li(t('即使你不打算接受竞争offer，有它就要用')),
  li(t('竞争offer应来自同等级别公司（Google vs Meta，而非Google vs 小startup）')),
  h3('没有竞争offer时的替代策略'),
  li(t('市场数据法：引用Levels.fyi P75数据作为对比基准')),
  li(t('经验溢价法：强调特定技能的市场稀缺性')),
  li(t('内部referral法：如有内部推荐人，请他们帮你游说')),
  li(t('时间压力法（谨慎用）：提及有其他公司在推进面试流程')),
  hr(),
  h2('五、按行业的谈判策略差异'),
  h3('科技公司（FAANG级别）'),
  li(t('最灵活，每年定期调薪，谈判文化成熟')),
  li(t('Recruiter有明确的"band"，通常在band内可以谈到P75')),
  li(t('RSU比base更好谈（公司会计处理不同）')),
  li(t('Signing bonus是最容易额外获得的部分')),
  li(t('策略：先谈base，再要signing，再要RSU refresh commitment')),
  h3('投资银行（BB/EB）'),
  li(t('Base salary高度标准化，几乎不能谈（analyst全员$110k-$125k）')),
  li(t('Signing bonus有一定空间（$10k-$30k）')),
  li(t('Group selection是比薪资更重要的谈判点（M&A vs Coverage）')),
  li(t('Start date和relocation可以谈')),
  h3('咨询公司（MBB/T2）'),
  li(t('Base完全标准化，不能谈')),
  li(t('Start date可以延迟（很多人gap半年）')),
  li(t('School matching可谈（不同学校cohort待遇）')),
  li(t('MBA后return offer：starting level可以谈')),
  h3('PE/VC/HF（Buy-side）'),
  li(t('小基金谈判空间极大，一切都可以谈')),
  li(t('Carry/carried interest是核心谈判点，但通常3-5年后才体现')),
  li(t('AUM percentage、co-investment rights也可提')),
  li(t('大基金（Blackstone/KKR）薪资相对固定')),
  hr(),
  h2('六、电话谈判实战脚本'),
  h3('场景1：要求更高base'),
  quote(t('"Hi [Recruiter], thank you again for the offer. I\'ve had a chance to review everything carefully. I\'m very excited about the role and the team. Based on my research and conversations with peers in similar roles, I was hoping to see the base salary closer to $[X]. Given my [specific experience], I think this is in line with market rates. Is there flexibility there?"')),
  h3('场景2：用竞争offer推高'),
  quote(t('"I wanted to be transparent with you — I do have another offer on the table from [Company]. The total comp is approximately $[X]. I genuinely prefer [Company] because of [specific reason], but I need to make sure I\'m not leaving too much on the table. Can we revisit the offer to make it more competitive?"')),
  h3('场景3：对方说"这是我们最好的offer"'),
  quote(t('"I appreciate you being straightforward. I understand there may be constraints on base salary. Would it be possible to look at other components — perhaps the signing bonus or an accelerated RSU grant? I want to make this work, and I\'m hoping we can find a way to close the gap."')),
  hr(),
  h2('七、真实数据：谈判结果案例'),
  li(t('Google L4 SWE：初始$180k → 谈判后$205k base + $30k extra signing（via competing Uber offer）')),
  li(t('Meta E5：$220k base + $300k RSU → 加了$50k RSU + $20k signing后接受')),
  li(t('McKinsey BA：base固定，谈到推迟8个月start date（去旅行）')),
  li(t('Goldman IBD Analyst：signing从$10k谈到$25k（凭Columbia vs Cornell学校差异）')),
  li(t('Citadel Quant：base + bonus结构谈到增加$25k 保底bonus（guaranteed first year）')),
  li(t('Amazon PM L6：谈到level upgrade（从L5录取 → 重新评估定L6），TC差距~$80k')),
];

// ============================================================
// 页面2：🎤 行为面试题库（200+真题+STAR答案框架）
// ============================================================
const behavioralInterviewBlocks: any[] = [
  p(t('来源：Amazon Leadership Principles官方指南、McKinsey/BCG面试prep材料、Google rater handbook、Reddit r/interviews真实面经、Career Cup整理，覆盖10大核心主题。', false, true)),
  hr(),
  h2('一、STAR框架深度讲解'),
  h3('STAR的四个层次'),
  li(t('S - Situation（情境）：'), t('具体场景，1-2句话，设置背景。避免"我们公司..."这种泛泛描述', true)),
  li(t('T - Task（任务）：'), t('你的具体职责和要达成的目标。突出"你"的角色，而非团队', true)),
  li(t('A - Action（行动）：'), t('你采取的具体步骤（占答案60%以上），用"I"而非"We"', true)),
  li(t('R - Result（结果）：'), t('量化结果，有数据最好。如果失败，说明你学到什么', true)),
  h3('STAR答案时间控制'),
  li(t('一般behavioral question：90秒-2分钟')),
  li(t('Amazon Leadership Principles深度追问：可到3-4分钟')),
  li(t('大忌：说了3分钟还没到Action部分')),
  quote(t('技巧：准备5-7个"核心故事"，每个故事可以回答3-4个不同问题。这叫"story banking"。')),
  hr(),
  h2('二、Amazon Leadership Principles 全16条真题库'),
  h3('LP1: Customer Obsession（客户至上）'),
  li(t('Tell me about a time you went above and beyond for a customer.')),
  li(t('Describe a situation where you had to make a decision that negatively impacted one group of customers to benefit another.')),
  li(t('Give me an example of when you used customer data to make a decision that others initially disagreed with.')),
  p(t('强答思路：强调主动收集客户反馈，不等客户抱怨就预判需求；量化客户满意度提升（NPS/CSAT）。')),
  h3('LP2: Ownership（主人翁精神）'),
  li(t('Tell me about a time you took ownership of a project that wasn\'t originally your responsibility.')),
  li(t('Describe a time you made a mistake that had significant consequences. What did you do?')),
  li(t('Give me an example of a time you stepped outside your job description to help the company.')),
  p(t('强答思路：展示没人分配但你主动承担；承担后果而非甩锅；长期影响而非短期任务。')),
  h3('LP3: Invent and Simplify（创新与简化）'),
  li(t('Tell me about an innovative solution you developed to solve a complex problem.')),
  li(t('Describe a time you simplified a process. What was the impact?')),
  li(t('Give an example of when you questioned the status quo and proposed a better way.')),
  h3('LP4: Are Right, A Lot（高判断力）'),
  li(t('Tell me about a time you had to make an important decision with incomplete information.')),
  li(t('Describe a situation where you changed your mind based on new data.')),
  li(t('Give an example of when your judgment was questioned by others but you turned out to be right.')),
  h3('LP5: Learn and Be Curious（好奇心）'),
  li(t('Tell me about a time you taught yourself a new skill to solve a problem.')),
  li(t('Describe how you stay current in your field.')),
  li(t('Give an example of a time curiosity led you to an unexpected insight.')),
  h3('LP6: Hire and Develop the Best（育才）'),
  li(t('Tell me about a time you coached or mentored someone and they improved significantly.')),
  li(t('Describe your approach to giving critical feedback.')),
  li(t('Give an example of when you identified talent in an unexpected place.')),
  h3('LP7: Insist on the Highest Standards（高标准）'),
  li(t('Tell me about a time you refused to compromise quality under time pressure.')),
  li(t('Describe a situation where you pushed back on a decision because standards were being cut.')),
  li(t('Give an example of implementing quality checks that others thought were excessive but proved necessary.')),
  h3('LP8: Think Big（大局思维）'),
  li(t('Tell me about a time you thought beyond your immediate project to see a bigger opportunity.')),
  li(t('Describe a bold proposal you made that others thought was too ambitious.')),
  li(t('Give an example of when long-term thinking conflicted with short-term goals. How did you handle it?')),
  h3('LP9: Bias for Action（行动力）'),
  li(t('Tell me about a time you had to make a decision quickly without all the information you wanted.')),
  li(t('Describe a time when you took calculated risk. What happened?')),
  li(t('Give an example of when moving fast led to an error. How did you recover?')),
  h3('LP10: Frugality（节俭）'),
  li(t('Tell me about a time you accomplished something significant with limited resources.')),
  li(t('Describe how you prioritize when you have more to do than time/budget allows.')),
  li(t('Give an example of a creative solution that saved significant cost.')),
  h3('LP11: Earn Trust（赢得信任）'),
  li(t('Tell me about a time you had to deliver bad news to stakeholders. How did you handle it?')),
  li(t('Describe a situation where you had to rebuild trust with a colleague or client.')),
  li(t('Give an example of when you admitted you were wrong publicly. What did you learn?')),
  h3('LP12: Dive Deep（深挖细节）'),
  li(t('Tell me about a time you uncovered a root cause that others had missed.')),
  li(t('Describe your process for getting into the details of a complex problem.')),
  li(t('Give an example of when a surface-level fix wasn\'t working and you had to dig deeper.')),
  h3('LP13: Have Backbone; Disagree and Commit（坚持立场+服从决定）'),
  li(t('Tell me about a time you disagreed with your manager. How did you handle it?')),
  li(t('Describe a situation where you had to support a decision you personally disagreed with.')),
  li(t('Give an example of when you pushed back successfully and changed a decision.')),
  h3('LP14: Deliver Results（结果导向）'),
  li(t('Tell me about your most significant accomplishment at your last job.')),
  li(t('Describe a time you had to overcome major obstacles to deliver a project.')),
  li(t('Give an example of when you failed to meet a goal. What did you do differently next time?')),
  h3('LP15: Strive to be Earth\'s Best Employer'),
  li(t('Tell me about a time you created a psychologically safe environment for your team.')),
  li(t('Describe how you\'ve handled a situation involving team wellbeing vs. deadline pressure.')),
  h3('LP16: Success and Scale Bring Broad Responsibility'),
  li(t('Tell me about a time you considered the broader societal impact of your work.')),
  li(t('Describe a decision where you balanced company profit with ethical responsibility.')),
  hr(),
  h2('三、通用Behavioral题（非Amazon特有）'),
  h3('团队冲突类（必考）'),
  li(t('Tell me about a time you had a conflict with a coworker. How did you resolve it?')),
  li(t('Describe a situation where you had to work with someone whose working style was very different from yours.')),
  li(t('Give an example of when you had to influence someone without direct authority.')),
  li(t('Tell me about a time a team member wasn\'t pulling their weight. What did you do?')),
  h3('领导力类'),
  li(t('Tell me about a time you led a project without formal authority.')),
  li(t('Describe a situation where you had to motivate a demoralized team.')),
  li(t('Give an example of a difficult decision you made as a leader.')),
  li(t('Tell me about a time your leadership style failed. What did you change?')),
  h3('失败与学习类（考官最看重的）'),
  li(t('Tell me about your biggest professional failure.')),
  li(t('Describe a project that didn\'t go as planned. What was your role?')),
  li(t('Give an example of when you received harsh feedback. How did you respond?')),
  li(t('Tell me about a time you had to learn from a mistake in a high-pressure situation.')),
  h3('优先级与压力类'),
  li(t('Tell me about a time you had too many competing priorities. How did you manage?')),
  li(t('Describe a time you had to say no to a request you couldn\'t accommodate.')),
  li(t('Give an example of working effectively under extreme pressure or tight deadline.')),
  li(t('Tell me about a time you had to pivot quickly due to changing circumstances.')),
  h3('数据与分析类（咨询/科技常见）'),
  li(t('Tell me about a time you used data to make a decision that went against intuition.')),
  li(t('Describe a complex analysis you conducted. Walk me through your methodology.')),
  li(t('Give an example of when you had to simplify complex data for a non-technical audience.')),
  li(t('Tell me about a time data showed you were wrong. How did you adjust?')),
  hr(),
  h2('四、高频追问（Follow-up Questions）应对'),
  h3('对方常见追问及对应策略'),
  li(t('追问："What would you do differently?" → 诚实反思，不要说"I wouldn\'t change anything"')),
  li(t('追问："What was the outcome?" → 必须有量化数据，哪怕是估算')),
  li(t('追问："What was your specific role vs. the team?" → 强调"I"，不要说"we"')),
  li(t('追问："How did you know it was successful?" → 说明成功标准是如何定义和测量的')),
  li(t('追问："Who else was involved?" → 展示collaborative能力但保持individual贡献清晰')),
  hr(),
  h2('五、各公司Behavioral面试特点对比'),
  h3('Amazon：最系统化'),
  li(t('所有面试官共同覆盖16个LP，不重复')),
  li(t('要求每个答案必须是"recent"（3年内）')),
  li(t('必须用STAR，用"I"而非"we"，否则被标注')),
  li(t('Bar Raiser轮会特别深挖你的"Think Big"和"Invent and Simplify"')),
  h3('McKinsey：PEI（Personal Experience Interview）'),
  li(t('三个固定维度：Personal Impact / Entrepreneurial Drive / Inclusive Leadership')),
  li(t('每个故事要展示你如何影响别人，必须有数字')),
  li(t('注重"what did YOU do"，不接受团队答案')),
  li(t('面试官会深挖到5-6层follow-up')),
  h3('Google：Googleyness + Leadership'),
  li(t('重视"Googleyness"：ambiguity中的舒适感、inclusive行为')),
  li(t('Leadership：即使是IC（individual contributor）也要展示影响力')),
  li(t('答案要有结构，但不需要严格STAR')),
  h3('Goldman/Morgan Stanley：Fit Interview'),
  li(t('Why this bank / Why IBD / Why this group：必须非常具体')),
  li(t('Tell me about yourself：2分钟完整pitch，从学校讲到现在')),
  li(t('知识类：你最近follow的一个deal是什么？你如何看待当前市场？')),
];

// ============================================================
// 页面3：🏢 FAANG深度文化手册（Google/Meta/Apple/Amazon/Netflix）
// ============================================================
const faangCultureBlocks: any[] = [
  p(t('来源：Glassdoor文化评分、Blind匿名员工反馈、Levels.fyi公司对比、ex-employee LinkedIn文章、"No Rules Rules"(Netflix书)、Amazon"Working Backwards"(Colin Bryar)，综合现任/前员工信息。', false, true)),
  hr(),
  h2('一、五家公司文化总体对比'),
  h3('Google（Alphabet）'),
  li(t('核心文化：'), t('"20% time"精神，鼓励创新，心理安全感高', true)),
  li(t('决策方式：'), t('Data-driven + consensus-seeking，决策慢但执行到位', true)),
  li(t('工作节奏：'), t('IC friendly，work-life balance相对好（但组间差异大）', true)),
  li(t('晋升机制：'), t('Peer review + manager review，需要internal visibility', true)),
  li(t('口碑：'), t('Glassdoor 4.3/5，Blind最常被吐槽"political"，"好人老好人"文化', true)),
  h3('Meta（Facebook）'),
  li(t('核心文化：'), t('"Move Fast and Break Things"（已调整）→ 现在"Move Fast"', true)),
  li(t('决策方式：'), t('Top-down（Zuckerberg影响力极强），执行速度快', true)),
  li(t('工作节奏：'), t('强度高，especially post-2022裁员后人少事多', true)),
  li(t('晋升机制：'), t('E4→E5是关键门槛，E5+需要"scope"扩展', true)),
  li(t('口碑：'), t('TC最高之一，但2022-2023裁员文化变了很多', true)),
  h3('Apple'),
  li(t('核心文化：'), t('极度保密（NDA文化），"Need to Know"，silos严重', true)),
  li(t('决策方式：'), t('Top-down，Steve Jobs遗风，设计优先', true)),
  li(t('工作节奏：'), t('因team差异极大（硬件vs软件vs服务），平均偏慢', true)),
  li(t('晋升机制：'), t('透明度低，manager依赖度高', true)),
  li(t('口碑：'), t('RSU折扣优惠好，但base相对低；产品自豪感极高', true)),
  h3('Amazon'),
  li(t('核心文化：'), t('Leadership Principles渗透一切，"Day One"精神', true)),
  li(t('决策方式：'), t('Data-driven + LP framework，大量内部6-pager写作', true)),
  li(t('工作节奏：'), t('强度高，"two-pizza team"小团队大责任', true)),
  li(t('晋升机制：'), t('SDE1→2→3→Principal，2年Up-or-Out压力', true)),
  li(t('口碑：'), t('Glassdoor 3.9/5（相对低），高离职率，高TC补偿', true)),
  h3('Netflix'),
  li(t('核心文化：'), t('"Freedom and Responsibility"——成年人文化', true)),
  li(t('决策方式：'), t('分散决策，信任每个人判断，几乎无流程', true)),
  li(t('工作节奏：'), t('结果导向，不考勤，无vacation policy（自主决定）', true)),
  li(t('晋升机制：'), t('无固定band，"Keeper Test"——你是否值得这份工资？', true)),
  li(t('口碑：'), t('Base salary业界最高（无RSU，全现金），高压高回报', true)),
  hr(),
  h2('二、Google深度解析'),
  h3('晋升到L5（Senior SWE）的现实'),
  li(t('L3（New Grad）→ L4 通常需要1-2年，表现好可以1年')),
  li(t('L4 → L5 是最大门槛，平均需要2-3年，很多人卡在L4')),
  li(t('L5 → L6 需要跨team影响力，很多人一辈子停在L5')),
  li(t('L5 TC：$350k-$500k（2024，湾区），包含base+bonus+RSU')),
  p(t('晋升关键：Promo Packet需要展示"Impact"——不是做了什么，而是影响了什么。需要peer pushback，需要manager提名，需要cross-team认可。')),
  h3('Google的"Perf"文化'),
  li(t('每半年一次Performance Review（Perf）')),
  li(t('结果：Needs Improvement / Meets / Exceeds / Strongly Exceeds / Outstanding')),
  li(t('"Exceeds"以上才有超额bonus和股票加速')),
  li(t('连续两次NI（Needs Improvement）会被PIP（Performance Improvement Plan）')),
  li(t('Calibration：你的打分会被你老板的老板calibrate，避免grade inflation')),
  h3('Google新员工必知的Noogler坑'),
  li(t('前3个月：找有经验的buddy，疯狂问问题，别自己摸索')),
  li(t('内部工具学习曲线陡峭：Piper/CitC/Blaze等，和外面完全不一样')),
  li(t('Team matching很重要：offer后有4-6周找team，多面几个team')),
  li(t('G2G（Google-to-Google）内部转组很灵活，1年后可申请')),
  hr(),
  h2('三、Meta深度解析'),
  h3('IC晋升路径（Engineering）'),
  li(t('E3（New Grad）→ E4：通常18个月，几乎是自动的')),
  li(t('E4 → E5：关键门槛，需要"impact at E5 scope"，通常需要2-3年')),
  li(t('E5 → E6（Staff）：影响力需超出单一team，非常难')),
  li(t('E5 TC（湾区）：$450k-$600k（2024）')),
  h3('Meta独特文化元素'),
  li(t('Bootcamp：所有新员工6周自选组，结束后选择team')),
  li(t('Hack-a-Month：可以短期加入任何team做黑客项目')),
  li(t('"People Manager"vs"IC Track"明确分开，不用管人也能升senior')),
  li(t('All Hands：Zuckerberg每周亲自开Q&A，相对开放')),
  li(t('2023后：10%+ layoff，culture更competitive，OKR更严格')),
  h3('Meta面试后的现实（Blind真实吐槽）'),
  li(t('工作强度：上午10点-晚上8点是标配，有些team更晚')),
  li(t('政治性：晋升需要"visibility"，写代码不够，要会"sell"自己')),
  li(t('RSU vesting：4年，cliff后有很多人立刻跳槽（"vest and leave"文化）')),
  hr(),
  h2('四、Amazon深度解析'),
  h3('6-Pager文化（独特的写作文化）'),
  li(t('Amazon开会不用PPT，用"6-pager"——6页书面文档')),
  li(t('会议开始前30分钟静默阅读6-pager')),
  li(t('好的6-pager：PR/FAQ（从新闻稿写起）、清晰数据、自我批评')),
  li(t('作为新员工：必须快速学会写6-pager，这是核心workplace skill')),
  h3('Amazon的OLR（Organizational Leadership Review）'),
  li(t('每年两次的"stack ranking"——所有人被分为Top/Middle/Bottom')),
  li(t('Bottom的人（约10-15%）会收到更密切的review')),
  li(t('连续Bottom可能导致离职压力（非官方up-or-out）')),
  li(t('这是Amazon高离职率的主要原因之一（平均tenure 1.8年）')),
  h3('SDE2→SDE3（Principal）路径'),
  li(t('SDE2 TC：$200k-$280k（Seattle，2024）')),
  li(t('SDE3：$280k-$380k，需要tech lead经验')),
  li(t('Principal SDE：$380k-$500k+，需要org-level影响力')),
  li(t('L7（Distinguished Engineer）：极少，年薪$600k+')),
  hr(),
  h2('五、Netflix深度解析'),
  h3('"Keeper Test"：你必须了解的文化核心'),
  quote(t('"If a person on your team was leaving for a similar job at another company, would you fight hard to keep them? If not, they should probably be let go now."')),
  li(t('这意味着：表现不够outstanding就会被let go，不是因为违规，而是"不够好"')),
  li(t('每个员工应该定期问自己："Would my manager pass the Keeper Test for me?"')),
  li(t('优势：促使公司保持高密度人才，避免"brilliant jerks"')),
  li(t('劣势：极高焦虑感，不适合不自信的人')),
  h3('Netflix的薪资哲学（全现金，无RSU）'),
  li(t('Netflix理念：给最高市场薪资的现金，让员工自己决定如何投资')),
  li(t('Senior SWE：$300k-$450k base（全现金）')),
  li(t('Staff Engineer：$400k-$600k base')),
  li(t('无保留期（retention）手段——唯一的保留是你真的喜欢这里')),
  li(t('可以选择部分工资用公司股票代替（按市价，无折扣）')),
  h3('Netflix的"No Rules Rules"文化实践'),
  li(t('无vacation policy：自己决定休多少假（实际平均15-20天/年）')),
  li(t('无报销审批：合理业务支出直接报，"Act in Netflix\'s best interest"')),
  li(t('信息极其透明：财务数据、战略方向，新员工都能看到')),
  li(t('招聘极严格：宁缺毋滥，每个open req都招顶级人才')),
  hr(),
  h2('六、中国背景求职者在FAANG的特别注意'),
  h3('文化差距填补'),
  li(t('主动表达：美国职场必须主动表达观点，不能等别人问你')),
  li(t('说"I"而非"We"：在绩效评价时，你必须能说清楚你自己的贡献')),
  li(t('Pushback文化：有不同意见要说出来，不说不等于同意，而是被认为没想法')),
  li(t('Meeting行为：会前准备，会中发言，会后follow-up——三步缺一不可')),
  h3('Visa相关的职业路径考量'),
  li(t('Google/Meta/Apple对H-1B最友好，有专门immigration团队协助')),
  li(t('Amazon也支持，但SDE团队immigration资源不如Google充足')),
  li(t('Netflix：H-1B友好，但因为文化高压，转visa压力更大')),
  li(t('Green Card（EB-1B/EB-2）：Google/Meta有项目帮助申请，timeline 2-5年')),
];

// ============================================================
// 页面4：🚀 创业与VC求职全攻略（Startup/风险投资）
// ============================================================
const vcStartupBlocks: any[] = [
  p(t('来源：Venture Capital Journal、AngelList talent数据、First Round Capital blog、a16z jobs、Sequoia招聘标准、LinkedIn求职者分析、Y Combinator资源库。', false, true)),
  hr(),
  h2('一、VC行业概览（对中国学生的特殊挑战）'),
  h3('VC求职的现实'),
  li(t('美国VC行业极小，全国真正的VC职位（非intern）约5,000个')),
  li(t('Top VC（a16z/Sequoia/Accel）不对外公开招聘，100%靠人脉')),
  li(t('国际学生难点：visa担保（很多小基金不sponsor H-1B）')),
  li(t('最常见入口：MBA → VC associate；或在startup做1-2年 → lateral move')),
  li(t('薪资：VC associate $150k-$200k + carry（5-10年后体现）')),
  h3('VC常见岗位类型'),
  li(t('Venture Analyst/Associate（Pre-MBA）：'), t('research、sourcing、portfolio support，$120k-$160k', true)),
  li(t('Senior Associate（Post-MBA）：'), t('lead deals，board observer，$170k-$220k', true)),
  li(t('Principal：'), t('独立sourcing，lead investments，$200k-$300k + carry', true)),
  li(t('VP/Partner：'), t('GP-track，$300k-$600k + significant carry', true)),
  hr(),
  h2('二、如何进入VC（实际路径分析）'),
  h3('路径1：MBA → VC Associate（主流路径）'),
  li(t('从M7 MBA（Wharton/HBS/GSB）申请VC associate最容易')),
  li(t('MBA期间务必：做VC club leader、完成VC实习、写investment thesis')),
  li(t('Top MBA VC club可以直接接触GP/Partner level')),
  li(t('成功率：M7 MBA + 强PE/IB背景 + VC实习 → 约20-30%的人能进VC')),
  h3('路径2：Startup → VC（越来越常见）'),
  li(t('在YC公司或知名startup做1-3年，了解builder视角')),
  li(t('最好在startup做growth/product/BD，而非纯工程')),
  li(t('成功条件：能展示deal flow network，有operator insight')),
  li(t('这个路径对没有IB背景的工科生友好')),
  h3('路径3：IB → PE → VC（传统金融路径）'),
  li(t('IB 2年 → PE 2-3年 → VC associate/principal')),
  li(t('这个路径在成长期投资（growth equity）更常见')),
  li(t('纯早期VC（pre-seed/seed）更喜欢operator背景')),
  h3('路径4：直接从Undergrad进入（极难）'),
  li(t('主要是做VC analyst（非投资，更多是research和admin）')),
  li(t('入口：学校VC club → 基金实习 → 转fulltime')),
  li(t('回报：经验积累，但薪资低（$80k-$100k），需要自己补充MBA或转型')),
  hr(),
  h2('三、VC面试内容与准备'),
  h3('Investment Thesis（核心考题）'),
  quote(t('"走我们看一个行业，你选一个你最感兴趣的赛道，说说为什么这是一个好的投资机会，以及你会如何筛选公司。"')),
  p(t('准备方法：')),
  li(t('选1-2个你深度研究过的赛道（AI/climate/healthcare/fintech）')),
  li(t('框架：市场大小（TAM）→ 时机（为什么是现在？）→ 竞争格局 → 优质创始人特征')),
  li(t('展示：你的独特观点，不是人云亦云的分析')),
  h3('Deal Sourcing（VC独特考核）'),
  li(t('VC面试会问：你如何找到好公司？你的deal flow从哪来？')),
  li(t('准备：列举3-5个你认识的创始人，或你参加的相关社区')),
  li(t('中国背景优势：熟悉中国科技生态，可以sourcing中国创始人在美创业')),
  h3('Portfolio Company Mock投资分析'),
  li(t('给你一家真实早期公司，1周时间做investment memo')),
  li(t('格式：Executive Summary → Team → Market → Product → Financials → Risks → Recommendation')),
  li(t('关键：清晰的Yes/No recommendation + 支撑逻辑，不要两头下注')),
  h3('Startup/Market知识测试'),
  li(t('最新融资新闻（Crunchbase/TechCrunch）要随时follow')),
  li(t('你们基金的portfolio company要深度了解')),
  li(t('如何区分"好市场"和"坏市场"：$10B+ TAM，winner-take-most dynamics')),
  hr(),
  h2('四、Startup求职（非VC）'),
  h3('如何找到好的Startup机会'),
  li(t('YC公司列表：ycombinator.com/companies，可按batch/industry筛选')),
  li(t('AngelList Talent（now Wellfound）：最多startup job listings')),
  li(t('LinkedIn筛选：Company size 11-50 + Funding stage Series A/B + Recent hiring')),
  li(t('通过VC网络：投资过的基金的portfolio company优先（referral易')),
  li(t('Hackathons：认识founder的最直接方式')),
  h3('如何评估Startup（Offer选择关键）'),
  li(t('融资情况：最近一轮是什么时候？pre/post-money valuation？跑道几年？')),
  li(t('Founder背景：是serial founder吗？技术背景？行业经验？')),
  li(t('市场：TAM是否足够大？有没有strong pull（而非push）？')),
  li(t('竞争：who are the competitors？为什么你们有差异化？')),
  li(t('你的role：是关键岗位还是边缘岗位？晋升路径清晰吗？')),
  h3('Stock Options vs RSU（Startup薪酬关键）'),
  li(t('Stock Options：需要行权（exercise），行权价是strike price，有时间限制（90天内离职后行权）')),
  li(t('RSU（私有公司）：越来越常见，但流动性取决于公司IPO/被收购')),
  li(t('Equity谈判：问清楚shares vs percentage；了解fully diluted cap table')),
  li(t('409A Valuation：决定行权价，越低越好（early join的优势）')),
  li(t('防水桶（anti-dilution）：理解你的股份在下轮融资中会被稀释多少')),
  hr(),
  h2('五、中国背景的VC/Startup独特优势'),
  h3('中美科技桥梁价值'),
  li(t('了解中国市场：很多美国VC开始关注中国创始人在美国的创业（AI、硬件）')),
  li(t('双语能力：能和中文创始人深入交流，获取一手信息')),
  li(t('跨境商业理解：供应链、制造、出海等赛道有独特视角')),
  h3('可以主攻的VC细分方向'),
  li(t('China-focused VC：GGV（现已分拆）、Qiming、ZhenFund美国office')),
  li(t('Deep Tech VC：对工程背景的中国学生友好（AI/biotech/climate')),
  li(t('Corporate VC（CVC）：腾讯/阿里/字节的美国投资部门（更容易进入）')),
  li(t('Family Office：部分华人family office在硅谷，小而精，更容易networking')),
  hr(),
  h2('六、VC求职时间线与实践'),
  h3('Pre-MBA阶段'),
  li(t('大三秋：开始关注VC club，参加pitch competitions')),
  li(t('大三春：申请VC summer internship（Sequoia Arc、a16z有项目）')),
  li(t('大四：拿到VC intern经验，决定直接进VC还是先去IB/PE')),
  h3('MBA期间'),
  li(t('第一学期：立刻加入VC/entrepreneurship club，争取leadership')),
  li(t('寒假：research基金、找alumni connection、做cold outreach')),
  li(t('第一年暑期：VC internship是关键，决定full-time offer可能性')),
  li(t('第二年秋：开始full-time recruiting，用intern公司作为anchor')),
  h3('关键资源'),
  li(t('Kauffman Fellows：VC行业最重要的项目，Alumni network极强')),
  li(t('VC Lab：online VC training，适合没有直接经验者')),
  li(t('Venture for America：适合undergrad进入创业生态')),
  li(t('BreakIntoVC：VC求职专门培训课程')),
];

// ============================================================
// 页面5：📧 求职邮件 + Cover Letter完整模板库
// ============================================================
const coverLetterBlocks: any[] = [
  p(t('来源：Harvard Business Review、Resume Worded、LinkedIn Job Search Guide、实际被录用的申请邮件模板，覆盖冷邮件、Networking邮件、Cover Letter各场景。', false, true)),
  hr(),
  h2('一、冷邮件（Cold Email）黄金模板'),
  h3('核心原则：短、具体、有价值'),
  p(t('黄金长度：不超过5句话。对方在手机上读，超过150字就没人看完。')),
  h3('模板1：向招聘经理的冷邮件'),
  quote(t('Subject: [Your Name] - [Target Role] Inquiry | [School] Alumni\n\nHi [Name],\n\nI\'m [Your Name], a [Year] [Degree] student at [School] with a background in [Relevant Experience]. I\'ve been following [Company]\'s work on [Specific Initiative/Product], and I\'m very interested in [Target Role].\n\nWould you have 15 minutes to share insights about [Specific Question about their work]? I\'d love to learn from your experience in [their specific role/area].\n\nThank you for your time.\n[Your Name] | [LinkedIn URL]')),
  h3('模板2：向校友的networking邮件'),
  quote(t('Subject: Fellow [School] Alum Seeking 15-Min Chat About [Industry]\n\nHi [Name],\n\nI came across your profile on LinkedIn and noticed we\'re both [School] alumni — small world! I\'m currently a [Year] student in [Program] and exploring opportunities in [Industry].\n\nYour experience at [Company] in [Role] is exactly the path I\'m hoping to pursue. Would you be open to a brief 15-minute call to share your journey? I have specific questions about [Topic 1] and [Topic 2] that I think you\'d be uniquely positioned to answer.\n\nNo worries if timing doesn\'t work — I truly appreciate any insights you could share.\n\n[Your Name] | [LinkedIn] | [Phone if appropriate]')),
  h3('模板3：有内推人时的申请邮件'),
  quote(t('Subject: Referral from [Referrer Name] – [Target Role] Application\n\nDear [Hiring Manager],\n\nI was referred to you by [Referrer Name], [their title] on your [team name] team. [Referrer] mentioned you\'re looking for someone with [Skill/Experience], and based on my background in [Relevant Area], they thought I\'d be a strong fit.\n\nI have [X years] of experience in [Core Competency], including [Specific Achievement with metrics]. I\'ve attached my resume and would welcome the opportunity to discuss how I can contribute to [Team/Company].\n\nBest regards,\n[Your Name]')),
  h3('模板4：LinkedIn InMail（字数更短）'),
  quote(t('Hi [Name], I\'m a [School] student interested in [Role] at [Company]. I\'d love to hear about your experience on the [Team] team — specifically [One Specific Question]. Would you have 15 minutes to chat? Happy to work around your schedule. Thank you!')),
  hr(),
  h2('二、Follow-Up邮件模板（避免追太紧）'),
  h3('面试后Thank You Note（24小时内发）'),
  quote(t('Subject: Thank You – [Position] Interview\n\nDear [Interviewer\'s Name],\n\nThank you for taking the time to speak with me today about the [Position] role. I especially enjoyed our conversation about [Specific Topic Discussed] — it reinforced my excitement about joining [Company].\n\nAfter our discussion, I\'m even more confident that my experience in [Relevant Skill] aligns well with what your team is building, particularly regarding [Specific Challenge They Mentioned].\n\nI look forward to hearing from you about next steps. Please don\'t hesitate to reach out if you need any additional information.\n\nBest regards,\n[Your Name]')),
  h3('一周无回音后的Follow-Up'),
  quote(t('Subject: Re: [Original Subject] – Quick Follow-Up\n\nHi [Name],\n\nI wanted to follow up on my application for [Position] submitted [Date]. I remain very interested in this opportunity and would love to discuss how my background in [Key Skill] could contribute to [Specific Team Goal].\n\nPlease let me know if there\'s any additional information I can provide. I\'m happy to be flexible with timing for next steps.\n\nThank you again for your consideration.\n[Your Name]')),
  h3('Offer Pending – 要求延长决定时间'),
  quote(t('Subject: [Position] Offer – Request for Extension\n\nDear [Recruiter Name],\n\nThank you so much for the offer to join [Company] as [Position]. I\'m genuinely excited about this opportunity.\n\nI\'m currently in late stages with another organization and want to make a fully informed decision. Could we extend the deadline to [Specific Date, 1-2 weeks out]? I want to give this the consideration it deserves.\n\nI\'m happy to discuss further if needed. Thank you for understanding.\n\n[Your Name]')),
  hr(),
  h2('三、Cover Letter完整指南'),
  h3('Cover Letter的现实：写还是不写？'),
  li(t('科技公司（Google/Meta/Amazon）：不需要，很少有人看')),
  li(t('投资银行/咨询公司：需要，会被认真阅读')),
  li(t('非营利/政府/教育机构：极为重要，有时比resume更重要')),
  li(t('小公司/startup：可以用来展示对公司的了解，有一定作用')),
  h3('Cover Letter结构（金融/咨询版）'),
  p(t('第一段（Why This Company + Why This Role）：')),
  quote(t('I am writing to express my strong interest in the Investment Banking Analyst position in the Technology Group at Goldman Sachs. Having followed Goldman\'s advisory work on transformative deals such as [Recent Deal], and given my background in technology and finance, I am confident I would contribute meaningfully to your team.')),
  p(t('第二段（Your Most Relevant Accomplishment）：')),
  quote(t('During my internship at [Company], I led a financial modeling project that identified $2.3M in cost optimization opportunities for a mid-cap healthcare company. I constructed a three-statement model and DCF analysis from scratch, ultimately presenting to the CFO and the firm\'s managing directors. This experience taught me to synthesize complex data under tight deadlines — skills I\'m eager to bring to Goldman.')),
  p(t('第三段（Why YOU are the right fit）：')),
  quote(t('Beyond technical skills, I offer [Company] a unique perspective as someone who has navigated both the technical rigor of a finance degree and hands-on experience building [product/startup]. My ability to communicate complex financial concepts to diverse audiences — from engineering teams to C-suite executives — has been consistently recognized as a differentiator.')),
  p(t('结尾段（Call to Action）：')),
  quote(t('I would welcome the opportunity to discuss how my background aligns with Goldman\'s needs. Thank you for considering my application — I look forward to speaking with you.\n\nSincerely,\n[Your Name]')),
  h3('Cover Letter常见错误（中国申请者高频犯）'),
  li(t('错误1：'), t('开头写"I am writing to apply for..."——这是废话，换成直接展示热情', true)),
  li(t('错误2：'), t('复述简历内容——CL要补充简历没说的，不是重复', true)),
  li(t('错误3：'), t('"I believe I would be a great fit..."——never say, show don\'t tell', true)),
  li(t('错误4：'), t('通篇谈自己，不提公司——必须体现你了解公司', true)),
  li(t('错误5：'), t('超过一页——一页是黄金，多了没人读', true)),
  li(t('错误6：'), t('语法/拼写错误——用Grammarly至少检查两遍', true)),
  hr(),
  h2('四、各行业Networking邮件实战策略'),
  h3('投资银行Networking邮件（最激烈竞争）'),
  li(t('Target：Associate level（2-4年经验），不要直接找MD')),
  li(t('最佳话题：他们经手的deals（Bloomberg/Dealogic查），工作风格，group culture')),
  li(t('禁忌：问"能帮我推荐吗？"——等对话之后再提')),
  li(t('节奏：每周networking 5-10个人，至少2个月，才能在招聘季有足够pipeline')),
  li(t('校友网络利用：LinkedIn筛选 School=你的学校 + Company=目标银行 + Year graduated=3-10年前')),
  h3('咨询公司Networking（MBB）'),
  li(t('重点：Coffee chat文化盛行，大部分人愿意接受30分钟chat')),
  li(t('话题：specific engagement（项目），industry focus，up-or-out culture真实体验')),
  li(t('注意：在MBB，referral确实有实质帮助，可以让简历过ATS')),
  li(t('内推流程：面聊2-3次 → 建立关系 → 对方主动提"我可以帮你refer"')),
  h3('科技公司Networking（更随意）'),
  li(t('LinkedIn上直接InMail，成功率约10-20%')),
  li(t('找校友成功率更高（同school filter）')),
  li(t('话题：team culture、tech stack、work-life balance真实情况')),
  li(t('目标：不需要直接问referral，对方印象好会主动提')),
  hr(),
  h2('五、邮件主题行（Subject Line）优化'),
  h3('高打开率的主题行公式'),
  li(t('"[共同点] – [你的身份] – [你的请求]"：Wharton Alum – PM @ Google – 15-Min Chat?')),
  li(t('"[具体问题]"：How did you transition from consulting to VC?')),
  li(t('"Referred by [共同认识的人]"：立刻提高40%+回复率')),
  li(t('"[职位] Application – [你的独特标识]"：PM Application – Ex-Founder, MIT \'23')),
  h3('低回复率的主题行（避免）'),
  li(t('"Just reaching out"——模糊无信息')),
  li(t('"Questions about your company"——太泛')),
  li(t('"Looking for opportunities"——太直白，让对方有压力')),
  li(t('"Hi"——直接被当垃圾邮件')),
  hr(),
  h2('六、LinkedIn消息 vs 邮件：如何选择'),
  h3('用LinkedIn InMail的场景'),
  li(t('找不到对方邮箱时')),
  li(t('对方最近在LinkedIn发布内容（说明他们活跃）')),
  li(t('职位较低的人（analyst/associate level）')),
  li(t('科技行业的人（LinkedIn文化更强）')),
  h3('用真实邮件的场景'),
  li(t('对方是MD/Partner/VP级别（更正式）')),
  li(t('金融/咨询行业（更traditional，用email')),
  li(t('你通过公司网站找到了邮箱（格式通常是firstname@company.com）')),
  li(t('通过校友数据库获取了邮箱（更正式关系，用email）')),
];

async function main() {
  console.log('🚀 开始写入深度内容（第五批）...\n');
  await createPage('💰 Offer谈判完整手册（美国求职实战）', offerNegotiationBlocks);
  await createPage('🎤 行为面试题库200+（Amazon LP+通用+各公司特点）', behavioralInterviewBlocks);
  await createPage('🏢 FAANG文化深度手册（Google/Meta/Apple/Amazon/Netflix）', faangCultureBlocks);
  await createPage('🚀 VC与Startup求职全攻略', vcStartupBlocks);
  await createPage('📧 求职邮件+Cover Letter完整模板库', coverLetterBlocks);
  console.log('\n✨ 完成！');
  console.log(`🔗 知识库：https://${DOMAIN}/wiki/Adh3w4XwCiMs2zkApVhcFdT0nFf`);
}

main().catch(console.error);
